### ISSUE TITLE
View search results with geo coordinates on a map (Openstreetmap)

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#103]
After different places with same names can be disambiguated with coming [Open Entity Search API](https://github.com/opensemanticsearch/open-entity-search-api) we can integrate a new [tab/view map where search result / documents with places can be shown on a Openstreetmap map](
https://github.com/opensemanticsearch/solr-php-ui/issues/45).

**Comment by Mandalka** [comment]
Documents with Geodata in the facet location_wkt_ss are shown now in the new view/tab map.
![map](https://user-images.githubusercontent.com/1010780/37525002-df074248-292b-11e8-9d3e-9111f974b0a4.png)
