### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#104]
Separation in / configuration of Docker containers for separation of services and easier deployment on (mutiple) server(s).

After more usage of/migration to REST-APIs / Microservices like https://github.com/opensemanticsearch/open-semantic-search-apps/issues/19 and implementation of [Open Semantic Entity Search API](https://github.com/opensemanticsearch/open-semantic-entity-search-api) separation in docker container should be easier, since generation/update of configs can be done on different/distributed servers over network.

**Comment by cedricwalter** [comment]
Hi

I can help for this as well, what is the status?

Regards

**Comment by cedricwalter** [comment]
you need help? i would like to use open semantic search in docker for a service i would like to launch....

**Comment by opensemanticsearch** [comment]
Can be done after https://github.com/opensemanticsearch/open-semantic-entity-search-api/issues/31 since getting rid of managing Solr config parts by editing Solr config files in filesystem by the Django web apps, since the new method of managing entities works full by Solr REST API, so the services can be separated in different Docker containers without same file system for multiple services.

**Comment by markedphillips** [comment]
Checking in on this status? I was thinking of building a similar docker container of all these parts and just exposing bind mounts for the documents to parse, index to write out, ports for web page. This would be useful for both Arm7_32 and x64.

**Comment by Mandalka** [comment]
Some of the most important steps toward easier running some of the services on separated docker containers/servers done by implementation of [handling of HTTP connection errors in ETL plugins/tasks now waits for microservices/REST APIs which are temporary not available](https://github.com/opensemanticsearch/open-semantic-etl/issues/84).

**Comment by opensemanticsearch** [comment]
Before all issues are solved to run all in separated containers, as first but fast step there will be an single container with all components next days after https://github.com/opensemanticsearch/open-semantic-search/issues/211 and https://github.com/opensemanticsearch/open-semantic-etl/issues/92.

**Comment by Mandalka** [comment]
Dependencies of other git repositories are now defined as submodules, so automatic resolution of dependencies possible.

**Comment by Mandalka** [comment]
Improved directory strucures and build scripts in the repositories to be more general / platform independent of the Debian configs/build scripts for easier collect files for the Docker container.

**Comment by Mandalka** [comment]
Official docker containers of base components we can integrate/reuse:

Solr (used by solr-php-ui, search apps and ETL): https://hub.docker.com/_/solr
RabbitMQ (used by search apps and ETL): https://hub.docker.com/_/rabbitmq

No official image for tika-server, but some inspiration/configs: https://hub.docker.com/search?q=tika-server&type=image

**Comment by Mandalka** [comment]
Docker Solr container preconfigured for Open Semantic Search now by extension of official Solr container by https://github.com/opensemanticsearch/solr.deb/blob/master/Dockerfile

**Comment by Mandalka** [comment]
Docker Solr container preconfigured for Open Semantic Search now by extension of official Solr container by https://github.com/opensemanticsearch/solr.deb/blob/master/Dockerfile

**Comment by Mandalka** [comment]
Added Open Semantic Entity Search API index schema to preconfigured Solr docker container https://github.com/opensemanticsearch/solr.deb/blob/master/Dockerfile so there is now an separated Docker container for Entities index and Solr tagger.

**Comment by Mandalka** [comment]
Configured Docker container for Open Semantic ETL by https://github.com/opensemanticsearch/open-semantic-etl/blob/master/Dockerfile

**Comment by Mandalka** [comment]
Configured Docker container for Apache Tika Server by https://github.com/opensemanticsearch/tika-server.deb/blob/master/Dockerfile

**Comment by Mandalka** [comment]
Making servers of microservices / REST-APIs like Solr, Tika, spaCy and Open Semantic Entity Search API configurable by environment variables, so we can configure them dynamic in/by Docker compose config without modifications of config files in containers by https://github.com/opensemanticsearch/open-semantic-etl/issues/100

**Comment by Mandalka** [comment]
Status: Most things run well in separated containers by coming docker-compose.yml and will be released soon.

Seems last problem beside some more time for trivial implementation of rest of https://github.com/opensemanticsearch/open-semantic-etl/issues/100 is that seems to be a problem to write to rabbitmq in a separated container from a Celery task imported in a Django app in a preforked Apache2 wsgi environment like used in the coming UI container:

rabbitmq_1  | 2019-11-27 17:03:46.614 [info] <0.454.0> accepting AMQP connection <0.454.0> (172.20.0.6:50436 -> 172.20.0.3:5672)
rabbitmq_1  | 2019-11-27 17:03:46.619 [info] <0.454.0> connection <0.454.0> (172.20.0.6:50436 -> 172.20.0.3:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1  | 2019-11-27 17:03:46.631 [info] <0.462.0> accepting AMQP connection <0.462.0> (172.20.0.6:50438 -> 172.20.0.3:5672)
rabbitmq_1  | 2019-11-27 17:03:46.634 [info] <0.462.0> connection <0.462.0> (172.20.0.6:50438 -> 172.20.0.3:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1  | 2019-11-27 17:03:46.656 [info] <0.483.0> accepting AMQP connection <0.483.0> (172.20.0.6:50440 -> 172.20.0.3:5672)
rabbitmq_1  | 2019-11-27 17:03:46.659 [info] <0.483.0> connection <0.483.0> (172.20.0.6:50440 -> 172.20.0.3:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1  | 2019-11-27 17:06:46.661 [error] <0.483.0> closing AMQP connection <0.483.0> (172.20.0.6:50440 -> 172.20.0.3:5672):
rabbitmq_1  | missed heartbeats from client, timeout: 60s



Please write me, if know a sustainable solution (i will search/debug tomorrow), if not easy solution maybe switch to Redis as message broker.

**Comment by Mandalka** [comment]
Workarround by initialization of Celery tasks for sending tasks to message queue in function while running calls instead global initialization in web app on start so on using web admin ui (which happens not often) it uses new RabbitMQ connection to prevent heartbeat problems and so closed connections to RabbitMQ if Celery in inactive preforked webserver environment.

**Comment by Mandalka** [comment]
Configured Docker container for Solr-PHP-UI and Open Semantic Search Apps and Open Semantic Entity Search REST-API by https://github.com/opensemanticsearch/open-semantic-search/blob/master/Dockerfile

**Comment by Mandalka** [comment]
Restructures some filenames/dirnames for data of Open Semantic Search Apps, so they can be easier separated in docker directory volumes by docker-compose to allow automatic updates of apps by docker pull without overwriting data or without need to manual upgrade the apps.

**Comment by Mandalka** [comment]
Configuration for docker-compose to integrate/run all separated services together by https://github.com/opensemanticsearch/open-semantic-search/blob/master/docker-compose.yml seems to work.

So yet to do only trivial environment settings implementations like https://github.com/opensemanticsearch/solr.deb/issues/8, https://github.com/opensemanticsearch/open-semantic-search-apps/issues/62 and rest of https://github.com/opensemanticsearch/open-semantic-etl/issues/100 before release next days.

**Comment by Mandalka** [comment]
Implemented https://github.com/opensemanticsearch/open-semantic-search-apps/issues/62 so Solr host used by Django search apps can be configured by environment variable set by docker-compose, too.

**Comment by Mandalka** [comment]
Configured Docker container for NER and sentence segmentation by spaCy in spacy-server by https://github.com/opensemanticsearch/spacy-services/blob/master/Dockerfile

**Comment by Mandalka** [comment]
Closing this old issue, since modernization / upgrades of Docker images by current issue #390.
