### ISSUE TITLE
Web User Interface for configuration of plugins and languages

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#105]
Thanks to different new translations and since more users from different countries who are not Linux admins, for easier configuration for end users / admins enable/disable some plugins like OCR and language settings should be configurable by an easy web user interface, instead of config files on command line or by text editor.

**Comment by Mandalka** [comment]
User interface is implemented in Open Semantic Search App [setup](https://github.com/opensemanticsearch/open-semantic-search-apps/tree/master/src/setup).

Todo:

- Generation of Open Semantic ETL config file
- Prefill config in DB with default settings

**Comment by Mandalka** [comment]
Generation of configs and includes in Open Semantic ETL and Solr-PHP-UI done.
