### ISSUE TITLE
Additional OCR dictionaries

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#109]
Addional to yet in the web admin user interface available OCR dictionaries add all other in Debian available OCR dictionaries to web admin user interface.
![ocr](https://user-images.githubusercontent.com/12616389/38803846-b7aa7cc6-4170-11e8-9163-cb81198aeb96.png)

**Comment by Mandalka** [comment]
All OCR dictionaries available by https://packages.debian.org/stable/tesseract-ocr-all are now listed in the web admin user interface.
