### ISSUE TITLE
Neo4j integration out of the box

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#110]
Neo4j (graph database and ETL plugin) installation, preconfigured and enabled by default.

**Comment by Mandalka** [comment]
Added web user interface for easier enabling & configuration of Neo4j ETL plugin.

**Comment by Mandalka** [comment]
Added link in search UI to Neo4j browser.

**Comment by Mandalka** [comment]
Added Neo4j server to Open Semantic Search package.
