### ISSUE TITLE
 open-semantic-search_18.05.06.deb / Ubuntu Xenial

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-search#111]
Installing throws the following error:

`default: Traceback (most recent call last):
    default:   File "/var/lib/opensemanticsearch/manage.py", line 10, in <module>
    default:     execute_from_command_line(sys.argv)
    default:   File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    default:     utility.execute()
    default:   File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 346, in execute
    default:     self.fetch_command(subcommand).run_from_argv(self.argv)
    default:   File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    default:     self.execute(*args, **cmd_options)
    default:   File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 445, in execute
    default:     output = self.handle(*args, **options)
    default:   File "/var/lib/opensemanticsearch/ontologies/management/commands/entities.py", line 11, in handle
    default:     self.stdout.write(self.style.SUCCESS('Setup done'))
    default: AttributeError: 'Style' object has no attribute 'SUCCESS'`

Ubuntu xenial installs django 1.8.7, which has no style.SUCCESS .  In this django version the format would be style.MIGRATE_SUCCESS.

**Comment by Mandalka** [comment]
Thank you for the bug report, removed class by https://github.com/opensemanticsearch/open-semantic-search-apps/commit/3280fae87e56a2300a2b9e31576f50e49957d230
