### ISSUE TITLE
Where can I find Queue manager and Scheduler?

### ISSUE THREAD

**Issue by memoday** [opensemanticsearch/open-semantic-search#12]
Hi admin,

I have added 2 rss feeds and I want to see how the results look like in Search, but I don't know how to commit these to Solr? How and where can I force the update of newly added feeds?

According to this page: https://opensemanticsearch.org/doc/modules

there should be 2 modules "Queue manager " and "Scheduler", but I cannot seem to find them. Where can I find them?

What command to use in crontab if I want to use cron?

It would be good to be able to trigger this functionality through user interface?

By the way, the link to ManifoldCF end user documentation in the following page under "Learn more" is broken. Can you please fix it?
Here is the broken URL used there.

https://manifoldcf.apache.org/release/trunk/en_US/end-user-documentation.html

One last thing and I don't want to create a new issue for it, but please let me know if this is what I supposed to do.

I cannot seem to find the link to "Delete" command that deletes Solr index.

According to this page https://opensemanticsearch.org/doc/admin/rest-api , it should be at this path:

http://127.0.0.1:/search-apps/api/delete, but nothing there.

Can you also please let me know how to enable remote access to Solr admin page? 

thanks,
Mohamed

**Comment by memoday** [comment]
By the way, I found this page https://opensemanticsearch.org/connector/rss

I don't see a Crawl button when I go to "http://localhost/search-apps/admin/rss_manager/"

I can only add or change RSS feeds, but now Crawl button to crawl the feeds. Any idea? Is there another path?

**Comment by opensemanticsearch** [comment]
Will write some examples for Celery based queue and Cron based scheduler config next week.

**Comment by opensemanticsearch** [comment]
The delete function of the API is only for single documents. If you want to delete the whole index, you have to use the Solr API, i write how to do that to the FAQ next week.

**Comment by Mandalka** [comment]
After swiching to RabbitMQ as celery broker (so you can use the now linked standard packages without additional config) i extended the documentation for [queuing](https://opensemanticsearch.org/doc/admin/config/queue) and [scheduling](https://opensemanticsearch.org/doc/admin/config/scheduler) to own pages.

In the next version there will be a preconfigured Cron job for RSS manager, so you don't have to call or configure a job for the import of RSS manager manually.

**Comment by Mandalka** [comment]
To enable Solr remote admin access from other computers than localhost you have to edit jetty-http.xml and delete the default="127.0.0.1" from the config option "host". Then restart Solr.

**Comment by opensemanticsearch** [comment]
Cron job for import of RSS feeds now default setup if using Debian or Ubuntu package or one of the VMs (release next days).

**Comment by memoday** [comment]
Thanks for the update. Please keep us posted when the new version is released. Is there any easy upgrade path from current version? 

Thanks
