### ISSUE TITLE
file monitoring remote doesn't see deleted files

### ISSUE THREAD

**Issue by aiscom** [opensemanticsearch/open-semantic-search#120]
Hallo!
i´ve installed opensemanticsearch-trigger-filemonitoring-daemon-remote_16.05.04_all.deb on Debian 9.
While installing, I get this error:
Paketes opensemanticsearch-trigger-filemonitoring-daemon-remote (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 127 zurück

Tried if it still works and the only problem I recognize is, that deleted files on fileserver are not removed from the remote search server. Adding files to the fileserver is no problem, thy are visible after few seconds on the remote search server search site.

**Comment by opensemanticsearch** [comment]
Think it was the bug in the REST-API https://github.com/opensemanticsearch/open-semantic-search-apps/issues/29.

Please reopen if new release doesn't solve this.
