### ISSUE TITLE
Disable Automatic Tagging

### ISSUE THREAD

**Issue by grplyler** [opensemanticsearch/open-semantic-search#126]
Hi,

Have googled and searched and read the docs to be best of my ability but I still cannot find where to disable this feature or if that is even possible. 

Basically, the functionality I am looking for is to disable the display of named entity recognition results and automatic tags. I would like only my custom tags to the display on the UI of the search index.

It possible to disable this feature or achieve this? 
Thanks in advance.

**Comment by rafael844** [comment]
https://github.com/opensemanticsearch/open-semantic-search/issues/130#issuecomment-430322845

To display I think this is what you need.

**Comment by YoannMR** [comment]
Hi,
You can turn off NER tagging from the UI (click on "Config" on the top right corner, then "Named Entity Recognition (NER)", then un-check "SpaCY NER").

To remove it from facet and snippet and add your own facet/snippet you can follow the link in rafael844's reply.

**Comment by opensemanticsearch** [comment]
NER by machine learning can be disabled in UI, the entity linking in ETL config.

The automatic tagging after saving will affect an different facet in future:

Will add ETL functionallity and an UI option to swich the view to "Manual tags" only by implementing https://github.com/opensemanticsearch/open-semantic-search/issues/142 next weeks, please see this issue for further development / to see when ready.

Index schema was prepared today.
