### ISSUE TITLE
How to disable Tesseract OCR and improve performance of indexing

### ISSUE THREAD

**Issue by dhruveshsheladiya** [opensemanticsearch/open-semantic-search#127]
I have data (pdf files) in bucket which is already OCRed with tesseract!! While indexing I don't want to run tesseract-OCR again on the same bucket!! 

Any suggestion for how to disable default OCR in OpenSemanticSearch??

**Comment by mosea3** [comment]
Hi Dhruvesh

Had a similar situation. 
I took out ocr out of the applying plugins list, as we OCR with propietary software.

Its an appliance-wide setting, so you can‘t define source-specific as far as I know. 

Best regards

Andy

**Comment by dhruveshsheladiya** [comment]
Thanks Andy for your response. Later on we found a similar solution to comment the OCR plugin from /etc/opensemanticsearch/connecterfiles and index the folder again!! 

We learned that 
   OpenSemanticSearch has OCR enable by default
   OCR with tesseract would consume lot of resources and CPU power and make indexing slow!! 
   OCRing images inside PDF would consume even more resources 
   
Best,
Dhruvesh

**Comment by opensemanticsearch** [comment]
Since some months you can disable OCR in the config web admin ui in tab OCR. If you disable it in plugins config the settings of the web UI (where OCR is on by default) will overwrite them.

OCR inside PDF can be disabled for defined paths by blacklisting the plugin for this file directories, but OCR for images yet only global since Tika doing it.

**Comment by Mandalka** [comment]
Now there is another way to do OCR later after all documents are indexed without OCR first, so you can work with most documents without have to wait for OCR without disable it: https://github.com/opensemanticsearch/open-semantic-search/issues/178
