### ISSUE TITLE
graph visualization

### ISSUE THREAD

**Issue by aiscom** [opensemanticsearch/open-semantic-search#129]
Hello!
How do I get graph visualization to work?
A new window opens, but I only see a small empty box.

Thanks

**Comment by skapi1992** [comment]
Same issue.

My steps:

1. I downloaded Open Semantic Search Appliance VM from:
[https://opensemanticsearch.org/download/#appliance](url)
2. I configured port forwarding in VirtualBox (Quest: 80, Host: 8099)
3. Run VM and log in as a root (username: "root", pass: "")
4. Start Chrome web browser and open [http://localhost:8099](url) and get access to the Open Semantic Search GUI
5. I go to "Datasource" tab and import http links which gathered some sample articles.
6. Entity extraction ("Persons", "Locations" etc.) goes well.
7. I open "Analyze" tab where I choose from dropdown menu "Connections (Graph)"
8. I check if there are entity types chosen on "Types of entities (classes) & connections (properties)" section
9. I click "Visualize graph starting with following (types and amount/limit of) entities" button

AND ... nothing. In attached screenshot I present new window with small empty box which appears after this steps.

<img width="1154" alt="small_empty_box" src="https://user-images.githubusercontent.com/8784569/46461738-b7bb8180-c7bf-11e8-8055-d1578283af3c.png">

What was next?

10. Read the doc one more time - decide to run Neo4j browser
11. Using Open Semantic Search GUI open "Config" and inside open "Graph DB (Neo4j)" tab. Click "enable" checkbox.
12. Forward ports on VirtualBox (Quest: 7474, Host: 7474)
13. Run "http://localhost:7474/browser/"

AND ... Page not exist

May I ask anyone to help in solving that issue somehow?

**Comment by Mandalka** [comment]
Added dependency cytoscape.js to static files in build script, so all next packages/releases/vms will include/install it automatically.
