### ISSUE TITLE
delete facets - OSS Desktop

### ISSUE THREAD

**Issue by rafael844** [opensemanticsearch/open-semantic-search#130]
Hello, newbie in OSS.

Trying to delete all the tags and facets author, person, message to... etc, from OSS Desktop, but didnt work. Tried it over django web UI, deleting all facets, but didnt work. Is it possible to do? 
Thats a lot of unnecessary information for us. And the tags some times increase too much. I would like to make a tag only with the folder where the file is in. is it possible?

Thanks

**Comment by YoannMR** [comment]
Hi,

You could manually modify the file /etc/solr-php-ui/config.facets.php

I tried commenting out the facets for "Persons" and "Organization" and they were removed from the UI.

//$cfg['facets']['person_ss'] = array ('label'=>'Persons', 'facet_limit'=>'10', 'snippets_limit'=>'10', 'graph_limit'=>'50','snippets_enabled'=>true,'graph_enabled'=>true);

//$cfg['facets']['organization_ss'] = array ('label'=>'Organizations', 'facet_limit'=>'10', 'snippets_limit'=>'10', 'graph_limit'=>'50','snippets_enabled'=>true,'graph_enabled'=>true);


It's not a clean way to do so though (there is a warning at the beginning of the file "// do not config here, this config file will be overwritten by Thesaurus and Ontologies Manager", so there might be a better way to do so.

I hope that helps a bit.

**Comment by rafael844** [comment]
Yes, thanks. That worked for me. I saw that config.facets.php but didnt want to change because of the warning, so I tried it from te web UI.

Now just trying to tag the folder the document is. The folder is an ID of a site, so if it could be "linkable" it would be nice. (f.e  d:/myfiles/9876/mydoc.pdf) Tag the folder, "SITE-INFO: 9876" and make it linkable.... www.mysite.com/view.php?id=9876, if dont, just the tag would be enough.

Any ideias of what files should I go for to try that? 

Thank you guys.

**Comment by YoannMR** [comment]
I'm not sure I understand what you mean.

If you index the folder using
opensemanticsearch-index-dir /myfiles/

and there are sub-folders such as /myfiles/9876/ you will see 'myfiles' in the 'Paths' facet on the UI. You can click on it to see the subfolders.

Is that what you want? Or do you want to create a new facet similar to 'Paths', called "SITE-INFO" and have it contain only the folder ID?

If that's the case, then you need to create a new field in the solr index that contains the site info and then create the facet as well.

ex in SOLR:
{
        "id":"/myfiles/9876/mydoc.pdf",
        "SITE_info_ss":"9876"}

for the facet, add a line to /etc/solr-php-ui/config.facets.php

$cfg['facets']['SITE_info_ss'] = array ('label'=>'SITE_info', 'facet_limit'=>'10', 'snippets_limit'=>'0', 'graph_limit'=>'50','snippets_enabled'=>false,'graph_enabled'=>true);

and to the file /etc/opensemanticsearch/facets, try adding
config['facets']['SITE_info_ss'] = {'label': 'SITE_info', 'uri': '', 'facet_limit': '10', 'snippets_limit': '10',}

**Comment by rafael844** [comment]
yes, its the second option, Im kind of new in this solr world, so Im still trying to figure it out.
I will try to find the file in solr to add that see how it is done. 

Thank you.

**Comment by Mandalka** [comment]
If you mean only the search UI and not the index:

If you don't want that the manual config will be overwritten by upgrades or add own facets, you can deactivate or add facets for the search UI by django admin in
http://localhost/search-apps/admin/thesaurus/facet/
by to deactivate setting the property "enabled" of the facet to false and if you dont want to see them as entities in result list snippets "snippets_enabled" to false, too.

**Comment by YoannMR** [comment]
I'd recommend starting by looking at the python code that does the indexing

/usr/lib/python3/dist-packages/opensemanticetl/etl_file.py

I believe that the code used to update the SOLR index is export_solr.py, so finding where it is called might help.

If you can't update the indexing code to handle this, you could write your own function (using export_solr.py) to add the field you need to the SOLR index for each document. It'd look something like this (sudo code)
  - run a SOLR query to find all documents that don't have any data in the field SITE_info_ss
  - for each docid do
    - connector = export_solr()
    - data = connector.get_data(docid, fields='')
    - data['SITE_info_ss'] = [docid.split('/')[1]] #add the field with value "9876"
    - connector.post(data=data, commit=True)

**Comment by YoannMR** [comment]
Actually, I think you might already have the information you need in the SOLR index

"path0_s":"myfiles",
"path1_s":"9876",

What you are looking for is "path1_s".

I'd try adding it to /etc/solr-php-ui/config.facets.php

$cfg['facets']['path1_s'] = array ('label'=>'SITE_info', 'facet_limit'=>'10', 'snippets_limit'=>'0', 'graph_limit'=>'50','snippets_enabled'=>false,'graph_enabled'=>true);

**Comment by rafael844** [comment]
ok, thank you very much for your help. It was great.
Ill try do that.

**Comment by starsnpixel** [comment]
rafael844, did you find an answer for your question "where to remove the "paths" and "file date" menu? neither, web UI or config.facets.php have this option"? I would like to do the same.

**Comment by rafael844** [comment]
> 
> 
> rafael844, did you find an answer for your question "where to remove the "paths" and "file date" menu? neither, web UI or config.facets.php have this option"? I would like to do the same.

no I didnt.

**Comment by Olydia** [comment]
You can remove the date facet from the IU directly from the code. 
You have to access /usr/share/solr-php-ui/templates/view.facet.php 
Comment or remove the lines 68-103 that deals with printing the date file "  <div id="file_modified_dt" class="facet">"
For path you have to look in the same class you will find the line that prints paths
