### ISSUE TITLE
Files & Directories (filesystem) - Missing delete function

### ISSUE THREAD

**Issue by konishiki** [opensemanticsearch/open-semantic-search#133]
You can add new file or directory, index now, edit settings however I cannot locate a delete function to remove.

**Comment by konishiki** [comment]
I finally found where to delete. It is in the Django admin interface. There is a need for improved documentation on the website when the project resources get the opportunity.

Keep up the good work!

**Comment by mosea3** [comment]
Hi, 

Please consult existing issues, like this one. 
https://github.com/opensemanticsearch/open-semantic-search-apps/issues/32

So, yes, its still to be implemented. 
Maybe, eventually, I will. 😅

Best regards

Andy Moser

**Comment by Mandalka** [comment]
Implemented a "Delete" link in the apps list view, so no need anymore to use the Django admin ui to delete entries.
