### ISSUE TITLE
Optional use of grammar/stemming for entity extraction

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#134]
Use of grammar/stemming for dictionary/ontology/thesaurus/lists of name based entity extraction.

**Comment by Mandalka** [comment]
After yesterdays migration to Solr Text Tagger for entity extraction, we can use multiple Solr analyzers / stemmers for entity extraction, too.

UI elements for easy setup of stemming added to Open Semantic Search Apps model and templates/form.

Todo: Options/Parameters for stemming in Open Semantic Entity Search API https://github.com/opensemanticsearch/open-semantic-entity-search-api/issues/34

**Comment by Mandalka** [comment]
Implemented automatic config of stemming in ETL plugin for entity extraction by ontologies settings in Ontology Manager web UI.

**Comment by Mandalka** [comment]
Stemming for entity extraction in ETL plugin now (optional) document language dependent.

**Comment by Mandalka** [comment]
Preconfigured some stemmers in Solr core for entities index. Using them by ETL plugin for named entity extraction can be activated for SKOS thesaurus or ontology by web config ui in Ontologies Manager.
