### ISSUE TITLE
Upgrade to Tesseract 4

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#136]
https://github.com/tesseract-ocr/tesseract/wiki/ReleaseNotes#tesseract-release-notes-oct-29-2018---v400

**Comment by Mandalka** [comment]
Open Semantic Desktop Search now uses Tesseract 4 from Debian backports.

**Comment by Mandalka** [comment]
Extended config UI / list of config options for OCR languages and scripts by new models from Tesseract 4 package https://packages.debian.org/stretch-backports/tesseract-ocr-all.

**Comment by Mandalka** [comment]
No backport repository anymore, since Tesseract 4 in Debian Stable.
