### ISSUE TITLE
How do I index second hard drive?

### ISSUE THREAD

**Issue by PeterausMG** [opensemanticsearch/open-semantic-search#138]
Hello
I am trying to index data on the second disk. I can access the disk. It is shared on the network, anyone can access the folder. I recognize that the new files should be indexed but no search results are displayed. What am I doing wrong?

**Comment by YoannMR** [comment]
What command are you using to index it?

**Comment by PeterausMG** [comment]
Hi YoannMR,
sudo opensemanticsearch-index-dir /media/peter/b18c25e2-5a36-4082-8785-2f9c41c895491/test
"test" is the name of the directory

thanks for help

**Comment by YoannMR** [comment]
Try opensemanticsearch-index-file /media/peter/b18c25e2-5a36-4082-8785-2f9c41c895491/test

If it works, it might be that celery does not have access right to this folder (try chmod -R 777 opensemanticsearch-index-dir /media/peter/b18c25e2-5a36-4082-8785-2f9c41c895491/test to see if that solves it)

**Comment by PeterausMG** [comment]
The command works, 
the following messages appear in the terminal:

Indexing new file: /media/peter/b18c25e2-5a36-4082-8785-2f9c41c895491/test/1.pdf
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Exception using Solr Text Tagger all_labels_stemming_force_de_ss_tag: 'response'
Exception using Solr Text Tagger all_labels_stemming_de_ss_tag: 'response'

The process takes a long time, It is a small file.

**Comment by YoannMR** [comment]
if you want to see what plugin are being used and may be taking a long time, you can enable verbose with
opensemanticsearch-index-file -v 

I suspect that OCR on images embedded in your pdf is what is taking a while. You can deactivate it from the UI (go to config > OCR, uncheck "OCR images in PDF"). I'd also recommend deactivating NER "Spacy NER"

**Comment by PeterausMG** [comment]
Thanks for your great and quick help
