### ISSUE TITLE
Set the default search option to AND instead of OR

### ISSUE THREAD

**Issue by dhyams** [opensemanticsearch/open-semantic-search#139]
The default searching uses OR to join words together; you have to explicitly go to "Search Options" and set the search conjunction to AND.  Most search engines use AND by default; how might one go about do this, or can it be fixed in the next release?

I believe that the intent in OpenSemanticSearch is to use AND by default.  At least that's what the Help documentation says that ships with OpenSemanticSearch.

**Comment by dhyams** [comment]
Mandalka: thanks so much!  Can you suggest where I might look to hack this functionality in until it is added to opensemanticsearch?

**Comment by dhyams** [comment]
Ah, nevermind!  It's in /usr/share/solr-php-ui/index.php, just set $operator = 'AND' instead of 'OR'. Sorry, I should have looked harder myself before posting.

**Comment by Mandalka** [comment]
Its set to AND in code and now a (more sustainable for the case upgrades) config option in config.php (maybe next year in web config ui, too).
