### ISSUE TITLE
Highlight not working

### ISSUE THREAD

**Issue by rgrativol** [opensemanticsearch/open-semantic-search#14]
The search works but the highlight is not being shown
![example](https://cloud.githubusercontent.com/assets/10871107/21969380/fffed3a8-db84-11e6-9170-50e78e392d71.jpg)
.

**Comment by opensemanticsearch** [comment]
No highlighting of terms yet which "only" found in enriched/filenames/pahts/analysis/metadata/ocr and not available in original main content

**Comment by Mandalka** [comment]
Another possibility why highlighting is not working even if search terms in main content is if stemming settings in Solr field content and field text differ. They have to be set to the same language and stemming settings before indexing documents.

**Comment by opensemanticsearch** [comment]
With Solrs new Highlighting component, the stemmed matches from other fields are highlighted, too without setup of stemming for the highlighted field.
