### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 500: Server Error (indexing not working anymore)

### ISSUE THREAD

**Issue by woxop** [opensemanticsearch/open-semantic-search#143]
I have an open-semantic-search server running since March on an up-to-date debian 9.6 VM (KVM) with more than 4 millions documents successfully indexed. Everything was running smoothly until a few days ago, but now indexing new files always results in an error (and the files are not indexed anymore):

```
 Traceback (most recent call last):
  File "/usr/bin/opensemanticsearch-index-dir", line 274, in <module>
    connector.commit()
  File "/usr/lib/python3/dist-packages/opensemanticetl/etl.py", line 295, in commit
    self.exporter.commit()
  File "/usr/lib/python3/dist-packages/opensemanticetl/export_solr.py", line 220, in commit
    request = urllib.request.urlopen( uri )
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Server Error
```
I have no idea what is wrong with my machine and what to look at. Adding more disk space as suggested in issue #115 did not solve the problem (I have 238GB free and 154GB used). The machine has plenty of RAM (15GB, but never uses more than 10) and 8 cores available from the host, and everything was running well for almost a year.

Thanks in advance for your help. I can provide more information if you need.

**Comment by YoannMR** [comment]
Have you tried re-starting the instance or restarting solr?
Is you solr server still working for searches and crashing only for indexing?
Are you indexing manually (sending the indexing command) or using file-monitoring?

You may have enough disk space but ran out of inodes (especially if you index a lot of small documents). Try the command df -i to see your inode usage.

**Comment by opensemanticsearch** [comment]
Which version of the debian package do you use?

If a newer one (where Solr log is active): Which error / exception is logged in Solr log /var/solr/logs/solr.log ?

**Comment by woxop** [comment]
I am not sure which version I use, but definitely not a newer one. How could I check?
There is no directory solr in /var/log
How could I manually activate solr logging?

**Comment by opensemanticsearch** [comment]
The directory is /var/solr/logs not /var/logs/solr.

But it seems its a very old search server package (yet Solr 6), there was an former issue with former single valued author field that if f.e. multiple authors (array instead of string) there was an exception on Solr import, so since some releases f.e. the field author is multivalued and some schema strucutred changed (so after upgrade to Solr 7 schema new indexing of all documents neccessary).

**Comment by opensemanticsearch** [comment]
Maybe you can see some error messages if you go to the Solr admin UI like http://localhost:8983/solr in the tab "Log" without have to access the log file in filesystem.

**Comment by woxop** [comment]
All right, I'll have a look this evening to the directory /var/solr/logs and localhost:8983/solr and report back what I found.

You think upgrading to solr 7 could maybe solve the problem? That would mean reindexing all documents?

**Comment by woxop** [comment]
This is  the content of /var/solr/logs, which log should I inspect and what should I look for?

```
ls -la
total 133760
drwxr-x--- 3 solr solr     4096 Dec  5 20:33 .
drwxr-x--x 4 solr solr     4096 Dec  4 22:20 ..
drwxr-x--- 2 solr solr     4096 Dec  4 22:20 archived
-rw-r--r-- 1 solr solr     1988 Dec  4 22:23 solr-8983-console.log
-rw-r--r-- 1 solr solr 20971701 Dec  5 04:12 solr_gc.log.0
-rw-r--r-- 1 solr solr 20973218 Dec  5 07:32 solr_gc.log.1
-rw-r--r-- 1 solr solr 20972434 Dec  5 10:48 solr_gc.log.2
-rw-r--r-- 1 solr solr 20973743 Dec  5 14:03 solr_gc.log.3
-rw-r--r-- 1 solr solr 20971921 Dec  5 17:18 solr_gc.log.4
-rw-r--r-- 1 solr solr 20972314 Dec  5 20:33 solr_gc.log.5
-rw-r--r-- 1 solr solr 11061867 Dec  5 22:16 solr_gc.log.6.current
-rw-r----- 1 solr solr     6854 Jan  8  2018 solr.log.1
```

**Comment by woxop** [comment]
Any idea?

**Comment by opensemanticsearch** [comment]
Works after upgrade to new release and Solr 7 in https://github.com/opensemanticsearch/open-semantic-search/issues/146.
