### ISSUE TITLE
PDF view

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#144]
Rich view of PDF in preview tab by deeper integration with PDF viewer

**Comment by Mandalka** [comment]
Embedded PDF viewer to preview tab, if PDF file.

Search query terms, their synonyms, SKOS thesaurus aliases, stemmed variants and lexemes like other (irregular) verb forms are highlighted in rich PDF preview.

The former view is in subtab "Plain text".
