### ISSUE TITLE
Exception while data enrichment  with plugin export_queue_files: [Errno 111] Connection refused (fresh install)

### ISSUE THREAD

**Issue by woxop** [opensemanticsearch/open-semantic-search#146]
I did a fresh install in a fresh debian 9.6 VM using the latest available opensemanticsearch package (open-semantic-search_18.11.23.deb).

The installation went well.

After the installation was complete, I tried to index some files in /usr/share/doc as per the documentation (https://www.opensemanticsearch.org/doc/admin/install/search_server). 

Each indexed document returns a "Exception while data enrichment  with plugin export_queue_files: [Errno 111] Connection refused" errror:

```
opensemanticsearch-index-dir /usr/share/doc
Indexing new file: /usr/share/doc/libisc-export160/changelog.Debian.gz
Exception while data enrichment of share/doc/libisc-export160/changelog.Debian.gz with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/libisc-export160/copyright
Exception while data enrichment of share/doc/libisc-export160/copyright with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/libisc-export160/changelog.gz
Exception while data enrichment of share/doc/libisc-export160/changelog.gz with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/tesseract-ocr-nep/changelog.Debian.gz
Exception while data enrichment of share/doc/tesseract-ocr-nep/changelog.Debian.gz with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/tesseract-ocr-nep/copyright
Exception while data enrichment of share/doc/tesseract-ocr-nep/copyright with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/hunspell-hu/changelog.Debian.gz
Exception while data enrichment of share/doc/hunspell-hu/changelog.Debian.gz with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/hunspell-hu/copyright
Exception while data enrichment of share/doc/hunspell-hu/copyright with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/hunspell-hu/changelog.gz
Exception while data enrichment of share/doc/hunspell-hu/changelog.gz with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/liblvm2app2.2/changelog.Debian.gz
Exception while data enrichment of share/doc/liblvm2app2.2/changelog.Debian.gz with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/liblvm2app2.2/copyright
Exception while data enrichment of share/doc/liblvm2app2.2/copyright with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/liblvm2app2.2/changelog.gz
Exception while data enrichment of share/doc/liblvm2app2.2/changelog.gz with plugin export_queue_files: [Errno 111] Connection refused
Indexing new file: /usr/share/doc/apache2-data/changelog.Debian.gz
Exception while data enrichment of share/doc/apache2-data/changelog.Debian.gz with plugin export_queue_files: [Errno 111] Connection refused

```
I am not sure what to do next. When I browse the server (localhost/search), I see that the files have been somewhat indexed, but there is no associated metadata as usual (authors, date, language, etc.) and I cannot browse them (404 not found) or preview them (no text, no meta, see images screenshots below).
![1](https://user-images.githubusercontent.com/45610756/49656302-ead6f700-fa34-11e8-9fbf-965d1ddf0822.png)
![2](https://user-images.githubusercontent.com/45610756/49656306-ed395100-fa34-11e8-851a-7384569015d4.png)
![3](https://user-images.githubusercontent.com/45610756/49656384-240f6700-fa35-11e8-9d8b-58133a9d3aef.png)

**Comment by opensemanticsearch** [comment]
Seems the rabbit-mq queue used to add files to processing queue for parallel document processing dont work. Maybe the rabbit mq db is corrupted.

I'll add documentation about how to delete the rabbit-mq db next days.

**Comment by opensemanticsearch** [comment]
You can check if the rabbit-mq is the problem if you use
opensemanticsearch-index-file /usr/share/doc
instead of
opensemanticsearch-index-dir /usr/share/doc
to index the directory which does'nt use it (but no parallel processing, so for many tasks only one CPU used/one file after antother is processed)

**Comment by woxop** [comment]
Sorry for late reply.
opensemanticsearch-index-file /usr/share/doc had the same problem.
I just decided to install it all over again (new VM). Now it's working. Something must have gone wrong during the initial install I guess. Now it seems to work.
