### ISSUE TITLE
Status page for ETL / document processing

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#155]
Status page showing count of now yet fully processed documents / running ETL tasks and occured ETL errors like failed plugins or access rights errors.

**Comment by Mandalka** [comment]
For monitoring the ETL queue: Open Semantic Desktop Search now integrates Flower out of the box on Port 5555 to show/monitor running & queued ETL tasks.

**Comment by Mandalka** [comment]
Linked to it in "Datasources" > "Queue"

**Comment by Mandalka** [comment]
Preview tab "Import & Analysis (ETL)" of search UI shows ETL status and error messages.

Listview / Search results show facet with / interactive filter for failed ETL plugins.

**Comment by MichaelGGeoda** [comment]
> For monitoring the ETL queue: Open Semantic Desktop Search now integrates Flower out of the box on Port 5555 to show/monitor running & queued ETL tasks.



> Linked to it in "Datasources" > "Queue"

When I press Datasource->Queue->Show running and open imports and analysis tasks (ETL tasks), Open Semantic Search takes me to localhost:5555/task and I'm getting error that connection is refused. Tried this on OVA downloaded from Opensemanticsearch.org.

**Comment by euanmacinnes** [comment]
> localhost:5555/task and I'm getting error that connection is refused


After installation, I did a 

`sudo netstat -ntlp | grep LISTEN `

then found that port 5555 wasn't open, and subsequently, flower wasn't installed. so, I needed to:

`sudo apt install python-flower`

This also installed celery which also appeared not to be installed with the "full package" (.deb)

then

`rabbitmq-plugins enable rabbitmq_management`

and finally, just 'flower' to then start it. 

This immediately enabled Search results, as well as the :5555 website (not restricted to localhost either, which is fine for my use)

**Comment by aabaenar** [comment]
Hello, I have a Ubuntu Server 18.04, I am trying to install ando I want to view the http://the-ip-address:5555 but this dont works, I follow the instructions of @euanmacinnes but this don't works. Can you help me please?

**Comment by euanmacinnes** [comment]
> Hello, I have a Ubuntu Server 18.04, I am trying to install ando I want to view the http://the-ip-address:5555 but this dont works, I follow the instructions of @euanmacinnes but this don't works. Can you help me please?

what's your output of :
sudo netstat -ntlp | grep LISTEN

Is port 5555 listed / available ? (it can also be a firewall blocking the port, e.g. ufw)

**Comment by MichaelGGeoda** [comment]
The @euanmacinnes solution worked for me.  Flower should run in a terminal window. If close the terminal, port 5555 becomes unavailable again.

**Comment by aabaenar** [comment]
@MichaelGGeoda Thanks, you if I run flower in my terminal I can access.

**Comment by opensemanticsearch** [comment]
Status of running task is provided by flower (see above).

Stati of yet open tasks (not yet runned plugins) can be easier analyzed and filtered by powerful Solr queries for the ETL status fields like the stati of failed plugins by swiitching  https://github.com/opensemanticsearch/open-semantic-search/issues/245 to default setting.

**Comment by Mandalka** [comment]
Implemented showing status of file import in main search UI, if still open text extraction tasks.

Optional/configurable by $cfg['etl_status_warning']
