### ISSUE TITLE
Enriching with OCR

### ISSUE THREAD

**Issue by hansdeferrante** [opensemanticsearch/open-semantic-search#157]
I have trouble enriching the index with OCR. I have disabled OCR in the UI. After building the index, I want to run OCR using the command
`opensemanticsearch-enrich --plugins=enhance_ocr,enhance_pdf_ocr`.

However, it gives me the following errors

Data enrichment query: content_type: image\/* AND NOT enhance_ocr_b:true
Enrichment of matches the following query:
((content_type: image\/* AND NOT enhance_ocr_b:true) OR ((content_type:application\/zip OR id:*.zip OR content_type:application\/vnd.ms-outlook-pst OR id:*.pst) AND NOT ((etl_enhance_ocr_b:true) AND (etl_enhance_pdf_ocr_b:true)))) AND NOT (container_s:*)
Traceback (most recent call last):
  File "/usr/bin/opensemanticsearch-enrich", line 389, in <module>
    etl.enrich()
  File "/usr/bin/opensemanticsearch-enrich", line 191, in enrich
    self.enrich_query(query)
  File "/usr/bin/opensemanticsearch-enrich", line 250, in enrich_query
    results = self.solr.search(query, **solrparameters)
  File "/usr/lib/python3/dist-packages/pysolr.py", line 634, in search
    response = self._select(params)
  File "/usr/lib/python3/dist-packages/pysolr.py", line 344, in _select
    return self._send_request('get', path)
  File "/usr/lib/python3/dist-packages/pysolr.py", line 332, in _send_request
    raise SolrError(error_message)
pysolr.SolrError: [Reason: undefined field content_type]

Is there something I am misunderstanding?

**Comment by opensemanticsearch** [comment]
The enrich component is outdated and will be redesigned / upgraded to the now used background parallel processing queue next week, where "First index all documents without OCR (but most data) fast, than OCR in background later for rest of infos" will be implemented.

**Comment by Mandalka** [comment]
Closing old issue, since OCR in later stage implemented by #178 and standard setting in [config UI](https://github.com/opensemanticsearch/open-semantic-search/blob/master/docs/doc/admin/config/README.md).
