### ISSUE TITLE
Hierarchy/Taxonomy/Tree/Subclasses for faceted search / interactive filters / named entity overviews

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/open-semantic-search#16]
Since thanks to [SKOS thesaurus](https://github.com/opensemanticsearch/open-semantic-search/issues/4) concepts or entities can now have relations like broader or narrower or a tree structure: Support this taxonomies/hierarchies and RDF (sub)classes in search UI for faceted search.

**Comment by Mandalka** [comment]
Abstracted special handled file path hierarchy facet to generic taxonomy facet type in search UI.

Todo:

- Configurable field suffix to support multi valued fields in index.
- Use the new UI / fill taxonomy/hierarchy fields for hierarchical data/properties like entities from ontologies or thesauri in Open Semantic ETL / Semantic Entity Search API
- Preconfigure path facet in Django facet web config UI/DB

**Comment by Mandalka** [comment]
Field suffix is now multivalued strings as default, only file path one valued string.

Search UI supports now multi value fields/facets for browsing/filtering taxonomies, so multiple hierarchies of categories can be used for a document in same facet.

**Comment by Mandalka** [comment]
Implemented integration of taxonomy from Thesaurus Manager UI with Open Semantic Entity Search API entities index.

**Comment by opensemanticsearch** [comment]
Read and import taxonomy structure from external thesauri/ontologies by Ontologies Manager (using [SolrOntologyTagger](https://github.com/opensemanticsearch/solr-ontology-tagger/issues/14) for import) to Open Semantic Named Entities Search API

**Comment by Mandalka** [comment]
Implemented for taxonomy of external SKOS thesaurus using properties skos:broader and skos:narrower.

**Comment by Mandalka** [comment]
Implemented adding taxonomy for tagging yet indexed documents by "Appy ontology to (old) documents", too (for the case you add an ontology after indexing of documents).

**Comment by Mandalka** [comment]
Implemented taxonomies by classes of ontologies by rdf:type and rdfs:subClassOf in Solr Ontology Tagger (exporting to Open Semantic Entity Search API index), used for import of external thesauri or ontologies.

**Comment by Mandalka** [comment]
The taxonomy facets are now configurated automatically for the search UI by Ontologies manager.
