### ISSUE TITLE
Desktop search - no search result returned

### ISSUE THREAD

**Issue by Jasmi77** [opensemanticsearch/open-semantic-search#164]
Successfully installed Desktop search app with VM and index PDF, Text documents - but when searching - no result is returned. Please help.

**Comment by opensemanticsearch** [comment]
Maybe ETL is running yet (which happens in background and can take much time if OCR active), the new release (next week) has new user interfaces / status pages where you can see what happend and what went wrong.

**Comment by Mandalka** [comment]
Did you have access to the files in the VM? Sometimes user forget to set "automount" on the file shares in Virtual Machine config.

There was an bug in tika-python in some environments with special chars in file names, which led to empty documents, too (but you would see etl errors in the facet).

If this was not one of this two problems and newest release doen't work, please reopen.
