### ISSUE TITLE
Sentence segmentation

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#167]
Like segmentation to single PDF pages, add ETL plugin for segmentation to single sentences so we can search/filter entities that occur in one sentence instead of only one document or page.

**Comment by Mandalka** [comment]
Extended Spacy Services with sentence segmentation REST-API in https://github.com/opensemanticsearch/spacy-services/commit/e12eac6ca6cc887785543c877f7f2103361e9be2

**Comment by Mandalka** [comment]
Implemented ETL Plugin https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/enhance_sentence_segmentation.py

**Comment by Mandalka** [comment]
Implemented setup UI option in https://github.com/opensemanticsearch/open-semantic-search-apps/commit/7571aa8a8d87bc5dcf5c198abdace429a0336ace
