### ISSUE TITLE
Issue with Solr

### ISSUE THREAD

**Issue by Mikelin97** [opensemanticsearch/open-semantic-search#170]
After I install Open Semantic Search on my server, I get the following error message when I log into my webpage: 
Apache_Solr_HttpTransportException: '0' Status: Communication Error in /usr/share/solr-php-ui/Apache/Solr/Service.php:338 Stack trace: #0 /usr/share/solr-php-ui/Apache/Solr/Service.php(1170): Apache_Solr_Service->_sendRawGet('http://localhos...') #1 /usr/share/solr-php-ui/index.php(1397): Apache_Solr_Service->search('*:*', 0, 10, Array) #2 {main}

Also, when I tried to index some files: I found the following error messages: 
Exception while data enrichment of file:///usr/share/doc/linux-modules-4.18.0-10-generic/changelog.Debian.gz with plugin filter_file_not_modified: <urlopen error [Errno 111] Connection refused>

**Comment by Mandalka** [comment]
Which release version?

Seems the Solr server is not up.

Full installation done (sometimes the Solr server installation script needs a q to end to print a Solr installer message) ?

Is Solr up for example http://localhost:8983/solr or http://servername:8983/solr ?
If yes, what is there in tab "log" ?

**Comment by Mikelin97** [comment]
> Which release version?
> 
> Seems the Solr server is not up.
> 
> Full installation done (sometimes the Solr server installation script needs a q to end to print a Solr installer message) ?
> 
> Is Solr up for example http://localhost:8983/solr or http://servername:8983/solr ?
> If yes, what is there in tab "log" ?

**Comment by Mikelin97** [comment]
The release version is 19.01.24. 

When I use the command: service solr status, I got: 

solr.service - LSB: Controls Apache Solr as a Service
   Loaded: loaded (/etc/init.d/solr; generated)
   Active: active (exited) since Wed 2019-04-03 05:21:52 UTC; 9h ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0 (limit: 1107)
   Memory: 0B
   CGroup: /system.slice/solr.service

Apr 03 05:21:19 vultr.guest solr[822]: *** [WARN] *** Your open file limit is currently 1024.
Apr 03 05:21:19 vultr.guest solr[822]:  It should be set to 65000 to avoid operational disruption.
Apr 03 05:21:19 vultr.guest solr[822]:  If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your p
Apr 03 05:21:19 vultr.guest solr[822]: *** [WARN] ***  Your Max Processes Limit is currently 3693.
Apr 03 05:21:19 vultr.guest solr[822]:  It should be set to 65000 to avoid operational disruption.
Apr 03 05:21:19 vultr.guest solr[822]:  If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your p
Apr 03 05:21:51 vultr.guest solr[822]: [578B blob data]
Apr 03 05:21:51 vultr.guest solr[822]: Started Solr server on port 8983 (pid=1183). Happy searching!
Apr 03 05:21:52 vultr.guest solr[822]: [14B blob data]
Apr 03 05:21:52 vultr.guest systemd[1]: Started LSB: Controls Apache Solr as a Service.

But it tells me the site cannot be reached, when I use  http://localhost:8983/solr (with localhost replaced by my server ip). 

Also, here is the error trace when I use the command: opensemanticsearch-enrich, 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4a3e1b7ac8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/opensemanticsearch/select/?q=%28%28%2A%3A%2A+AND+NOT+%28etl_enhance_extract_text_tika_server_b%3Atrue%29%29+OR+%28%28content_type%3Aapplication%5C%2Fzip+OR+id%3A%2A.zip+OR+content_type%3Aapplication%5C%2Fvnd.ms-outlook-pst+OR+id%3A%2A.pst%29+AND+NOT+%28%28etl_enhance_extract_text_tika_server_b%3Atrue%29+AND+%28etl_enhance_rdf_annotations_by_http_request_b%3Atrue%29+AND+%28etl_enhance_rdf_b%3Atrue%29+AND+%28etl_enhance_pdf_ocr_b%3Atrue%29+AND+%28etl_enhance_regex_b%3Atrue%29+AND+%28etl_enhance_entity_linking_b%3Atrue%29+AND+%28etl_enhance_ner_spacy_b%3Atrue%29+AND+%28etl_export_neo4j_b%3Atrue%29%29%29%29+AND+NOT+%28container_s%3A%2A%29&fl=id&rows=100&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4a3e1b7ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pysolr.py", line 366, in _send_request
    timeout=self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/opensemanticsearch/select/?q=%28%28%2A%3A%2A+AND+NOT+%28etl_enhance_extract_text_tika_server_b%3Atrue%29%29+OR+%28%28content_type%3Aapplication%5C%2Fzip+OR+id%3A%2A.zip+OR+content_type%3Aapplication%5C%2Fvnd.ms-outlook-pst+OR+id%3A%2A.pst%29+AND+NOT+%28%28etl_enhance_extract_text_tika_server_b%3Atrue%29+AND+%28etl_enhance_rdf_annotations_by_http_request_b%3Atrue%29+AND+%28etl_enhance_rdf_b%3Atrue%29+AND+%28etl_enhance_pdf_ocr_b%3Atrue%29+AND+%28etl_enhance_regex_b%3Atrue%29+AND+%28etl_enhance_entity_linking_b%3Atrue%29+AND+%28etl_enhance_ner_spacy_b%3Atrue%29+AND+%28etl_export_neo4j_b%3Atrue%29%29%29%29+AND+NOT+%28container_s%3A%2A%29&fl=id&rows=100&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4a3e1b7ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/opensemanticsearch-enrich", line 389, in <module>
    etl.enrich()
  File "/usr/bin/opensemanticsearch-enrich", line 191, in enrich
    self.enrich_query(query)
  File "/usr/bin/opensemanticsearch-enrich", line 250, in enrich_query
    results = self.solr.search(query, **solrparameters)
  File "/usr/lib/python3/dist-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/python3/dist-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/python3/dist-packages/pysolr.py", line 375, in _send_request
    raise SolrError(error_message % params)
pysolr.SolrError: Failed to connect to server at 'http://localhost:8983/solr/opensemanticsearch/select/?q=%28%28%2A%3A%2A+AND+NOT+%28etl_enhance_extract_text_tika_server_b%3Atrue%29%29+OR+%28%28content_type%3Aapplication%5C%2Fzip+OR+id%3A%2A.zip+OR+content_type%3Aapplication%5C%2Fvnd.ms-outlook-pst+OR+id%3A%2A.pst%29+AND+NOT+%28%28etl_enhance_extract_text_tika_server_b%3Atrue%29+AND+%28etl_enhance_rdf_annotations_by_http_request_b%3Atrue%29+AND+%28etl_enhance_rdf_b%3Atrue%29+AND+%28etl_enhance_pdf_ocr_b%3Atrue%29+AND+%28etl_enhance_regex_b%3Atrue%29+AND+%28etl_enhance_entity_linking_b%3Atrue%29+AND+%28etl_enhance_ner_spacy_b%3Atrue%29+AND+%28etl_export_neo4j_b%3Atrue%29%29%29%29+AND+NOT+%28container_s%3A%2A%29&fl=id&rows=100&wt=json', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/opensemanticsearch/select/?q=%28%28%2A%3A%2A+AND+NOT+%28etl_enhance_extract_text_tika_server_b%3Atrue%29%29+OR+%28%28content_type%3Aapplication%5C%2Fzip+OR+id%3A%2A.zip+OR+content_type%3Aapplication%5C%2Fvnd.ms-outlook-pst+OR+id%3A%2A.pst%29+AND+NOT+%28%28etl_enhance_extract_text_tika_server_b%3Atrue%29+AND+%28etl_enhance_rdf_annotations_by_http_request_b%3Atrue%29+AND+%28etl_enhance_rdf_b%3Atrue%29+AND+%28etl_enhance_pdf_ocr_b%3Atrue%29+AND+%28etl_enhance_regex_b%3Atrue%29+AND+%28etl_enhance_entity_linking_b%3Atrue%29+AND+%28etl_enhance_ner_spacy_b%3Atrue%29+AND+%28etl_export_neo4j_b%3Atrue%29%29%29%29+AND+NOT+%28container_s%3A%2A%29&fl=id&rows=100&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4a3e1b7ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by noerv** [comment]
You must open a tunnel if you are not on the same server. This can be done with PUTTY. 
The following source helped me: https://blog.devolutions.net/2017/4/how-to-configure-an-ssh-tunnel-on-putty

**Comment by Mandalka** [comment]
You can access the solr log files on file system on the server in /var/solr/logs or allow other IPs to access the Solr admin UI in config file jetty-http.xml

If you have Solr on another server than ETL, the ETL host has to get access to the Solr server in config jetty-http.xml (by default only localhost has access to the Solr server).

Please reopen, if yet problems with newest release, no clear answer whats the problem for Solr logs or allowing ETL server IP in jetty-http.xml config if on different servers.

**Comment by danielrosero** [comment]
> You can access the solr log files on file system on the server in /var/solr/logs or allow other IPs to access the Solr admin UI in config file jetty-http.xml
> 
> If you have Solr on another server than ETL, the ETL host has to get access to the Solr server in config jetty-http.xml (by default only localhost has access to the Solr server).
> 
> Please reopen, if yet problems with newest release, no clear answer whats the problem for Solr logs or allowing ETL server IP in jetty-http.xml config if on different servers.

Hi @Mandalka , I'm trying to expose solr server to be accessed from outside localhost, but I still don't manage to find this jetty-http.xml file.

Can you help me out? Best regards

**Comment by danielrosero** [comment]
> > You can access the solr log files on file system on the server in /var/solr/logs or allow other IPs to access the Solr admin UI in config file jetty-http.xml
> > If you have Solr on another server than ETL, the ETL host has to get access to the Solr server in config jetty-http.xml (by default only localhost has access to the Solr server).
> > Please reopen, if yet problems with newest release, no clear answer whats the problem for Solr logs or allowing ETL server IP in jetty-http.xml config if on different servers.
> 
> Hi @Mandalka , I'm trying to expose solr server to be accessed from outside localhost, but I still don't manage to find this jetty-http.xml file.
> 
> Can you help me out? Best regards

If this help anyone, the file is located here: `/opt/solr/server/etc`

Just change the line: 
`<Set name="host"><Property name="jetty.host" default="127.0.0.1"/></Set>`

to:
`<Set name="host"><Property name="jetty.host" default="0.0.0.0"/></Set>`
