### ISSUE TITLE
Reindex files on recrawl if additional plugins configured

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#171]
If additional plugin like OCR was enabled, [reindex/ETL again](https://github.com/opensemanticsearch/open-semantic-etl/issues/87) files so the analysis of the additional plugin will be applied to yet indexed documents.

**Comment by Mandalka** [comment]
Implemented by https://github.com/opensemanticsearch/open-semantic-etl/commit/7e725c9064314fc2881ef75e1eaeff40874c46c9
