### ISSUE TITLE
Only index file name

### ISSUE THREAD

**Issue by bssher** [opensemanticsearch/open-semantic-search#174]
Is it possible to only index some file types with their name, not attempt to pull any of the data inside of the file?

**Comment by Mandalka** [comment]
Index the filenames before ETL will be new default setting by https://github.com/opensemanticsearch/open-semantic-search/issues/245 which will be part of next release.

You can additionally blacklist file types for all plugins which do some kind of extraction https://opensemanticsearch.org/doc/admin/config/blacklist
