### ISSUE TITLE
Tagging issues

### ISSUE THREAD

**Issue by hmottestad** [opensemanticsearch/open-semantic-search#177]
Hi,

I'm having trouble with tagging. 

I've made a litte video: https://youtu.be/xT8oRAU_b2Q

The issues are:
 - tagging a value from a field duplicate that value in a new field called "tags" instead of allowing to filter on the value from the field where it belongs
 - some values can not be used for tagging, though there does not seem to be any reason for why or why-not.

**Comment by Mandalka** [comment]
Tagging code was rewritten (new ETL plugin and bugfixes in search apps), please reopen if yet problems with current deb package or new desktop vm release next days.

**Comment by hmottestad** [comment]
Thanks @Mandalka !

It's been a few years now since I tried out Open Semantic Search. I'll try to see if I can't give it another try soon :)
