### ISSUE TITLE
SPARQL query/filter in Ontologies manager

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#18]
Allow to config a SPARQL query to fetch ontologies or ontology parts from a triplestore or to filter the ontology by (complex) SPARQL queries.

So it will be possible to use only filtered parts of ontologies or ontologies from triplestores without managing the SPARQL queries/filters and downloads by external tools.

**Comment by Mandalka** [comment]
Done for [this order/issue](https://github.com/opensemanticsearch/open-semantic-search/issues/62).
