### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by rusty9283** [opensemanticsearch/open-semantic-search#180]
Hello,
I tried the new version but now i get this failure:

```
Setting up open-semantic-search (19.05.19) ...
The system user `tika' already exists. Exiting.
daemon: fatal: failed to find pid for tika: No such file or directory
dpkg: error processing package open-semantic-search (--configure):
 installed open-semantic-search package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 open-semantic-search
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I hope you can hlep me please.

**Comment by Mandalka** [comment]
Migrated Tika service management / startup on boot from older Debian package "daemon" in init.d sctript to modern systemd service config in https://github.com/opensemanticsearch/open-semantic-search/issues/181.

Todays (or tomorrow) new package release should solve this issue which occurs if upgrading on Ubuntu without manual killing former installed Tika.

**Comment by Mandalka** [comment]
New package which is not using deprecated package "deaemon" anymore but systemd configs so upgrading and restarting services possible without manual killing or reboots is available for download.

**Comment by rusty9283** [comment]
it works now great - THANK YOU!!!
