### ISSUE TITLE
Migrate starting services from daemon package to systemd config

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#181]
The old debian package daemon used for starting services causes problems on newer Debian and Ubuntu releases, since stopping the services doesn't work, which causes problems like https://github.com/opensemanticsearch/open-semantic-search/issues/180 or https://github.com/opensemanticsearch/tika-server.deb/issues/5 and https://github.com/opensemanticsearch/tika-server.deb/issues/2.

Should be fixed by migration from "daemon" to systemd config https://wiki.debian.org/systemd/Services https://wiki.ubuntuusers.de/Howto/systemd_Service_Unit_Beispiel/

**Comment by Mandalka** [comment]
Migrated startup of Apache Tika to systemd service config instead of using Debian package daemon in init.d script.

**Comment by Mandalka** [comment]
Migrated service for task workers of Open Semantic ETL to systemd service config: https://github.com/opensemanticsearch/open-semantic-etl/issues/89

**Comment by Mandalka** [comment]
Removed dependency to old Debian package "daemon".

**Comment by Mandalka** [comment]
Migrated Spacy services daemon to systemd service config in https://github.com/opensemanticsearch/spacy-services.deb/issues/7
