### ISSUE TITLE
Upgrade spacy-services

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#185]
Upgrade spacy-services Deb package to new release of spacy-services which uses newer Spacy models (so old ones which were loaded by spacy services not available any more after installation of newest spacy).

**Comment by Mandalka** [comment]
Upgraded to newest spacy-services release, so spacy-services.deb used by ETL Spacy NER plugin runs on newest Spacy release, too.

**Comment by Mandalka** [comment]
Problem was not by old spacy-services or models, but dependencies / version conflicts with newer releases of falcon and/or hug.

Have to resolve version conflicts of packages (mixed from Debian repository and pip3 repositories).

**Comment by Mandalka** [comment]
Handling of dependencies for spacy-services.deb now by Pip on (pinned versions in) requirements.txt of dispacy app of spacy-services.
