### ISSUE TITLE
Russian stemming

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#186]
Add Russian grammar config.

**Comment by Mandalka** [comment]
Added Russian stemming for search with synonyms to Solr managed-schema.

**Comment by Mandalka** [comment]
Added Russian to Open Semantic ETL configs.

**Comment by Mandalka** [comment]
Added Russian language as option to setup / web admin UI.

**Comment by Mandalka** [comment]
Added new Solr fields for Russian stemming to search UI config.

**Comment by Mandalka** [comment]
Activated Russian stemming by default in Web admin UI so it gets active if language detection for document returns ru.

If you upgrade an existing installation or want force Russian stemming for all documents, you have to enable it in Web admin UI in menu Config > Document languages.

**Comment by Mandalka** [comment]
Added Russian stemming for dictionary based entity extraction (Added Tagger for SKOS thesaurus, RDF ontologies and entity lists based entity extraction with Russian stemming in Solr managed-schema of Open Semantic Entity Search API).

**Comment by Mandalka** [comment]
Added option in Ontologies Manager UI to enable Russian stemming for ontology based entity extraction.
