### ISSUE TITLE
Blacklist with all filetypes?

### ISSUE THREAD

**Issue by rusty9283** [opensemanticsearch/open-semantic-search#188]
Hello!
We are indexing our hole server with about 2 million files but there are files which shouldn't be indexed.

I know there is a blacklist to ignore filetypes but is it possible to ignore ALL filetypes like ".*" and add only some filetypes like .pdf .doc in the whitelist? - so only the filetypes in the whitelist will indexed.

Thanks!

**Comment by Mandalka** [comment]
* is not supported in blacklists for suffixes. But you can add a Regex matching all urls/filenames to the regex blacklist /etc/opensemanticsearch/blacklist/blacklist-url-regex and then whitelist all suffixes (warning: case sensetive, so all variants have to be listed) like
.pdf
.PDF
.Pdf

 in the suffixes whitelist /etc/opensemanticsearch/blacklist/whitelist-url-suffix.
