### ISSUE TITLE
Configure PIP dependencies / packages

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#193]
Confgure Python PIP dependencies, so automatic dependencies resolution by PIP possible, if not using the Debian packages (which then will use the pip dependencies config instead of pip install for each package which not available as Debian package).

**Comment by Mandalka** [comment]
First done for spacy-services.deb now using
pip3 install -r /usr/lib/python3/dist-packages/spacy-services/displacy/requirements.txt
called in postinst.

**Comment by Mandalka** [comment]
Configured [pip requirements for Open Semantic ETL](https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/requirements.txt) by https://github.com/opensemanticsearch/open-semantic-etl/issues/92.
