### ISSUE TITLE
Upgrade to Debian 10

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#195]
Make Open Semantic Search runnable on new stable release Debian 10 and its libraries/versions out of the box by solving issues like https://github.com/opensemanticsearch/open-semantic-search-apps/issues/57

**Comment by Mandalka** [comment]
New beta release of the Debian package should run on Debian 10 out of the box.

Will do some more test next week.

Please reopen if yet some issues on Debian 10.
