### ISSUE TITLE
Import/crawling tasks by datasources UI doesn't work

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#196]
Import tasks added to queue by datasources UI instead of commandline tools doesn't work.

Maybe because explicit named/priorized queue in newer Open Semantic ETL releases.

Add explicit queue name parameter to Django search apps, too.

**Comment by Mandalka** [comment]
Added explicit queue names for new priorized document processing queue of Open Semantic ETL worker.

**Comment by Mandalka** [comment]
Another issue only appearing on the server not desktop (using only localhost/one IP) after upgrade to Debian 10 the HTTP API calls did'nt work becaue of Apache WSGI/Django config issues if accessed by other IPs, too. Was solved in https://github.com/opensemanticsearch/open-semantic-search-apps/issues/57.
