### ISSUE TITLE
Embed full documentation in releases

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#2]
Since there is not only fulltext search but more and more features, we have to export the documentation from (Drupal powered) website to local HTML files.

So in future by clicking "Help" you can access the full documentation (at the moment only the very short help text) offline or within your intranet, without accessing a public website.

**Comment by Mandalka** [comment]
Downloaded quick and dirty by wget --mirror --convert-links --html-extension --page-requisites --no-parent http://opensemanticsearch.local/doc/ so you collaboration and improves of the documentation by pull requests are possible in new repository https://github.com/opensemanticsearch/open-semantic-search-doc

**Comment by Mandalka** [comment]
Done by #392
