### ISSUE TITLE
UI: Normalized entities for navigation / faceted search / interactive filters

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#20]
For navigation, interactive filtering and aggregated overview use mainly the facet with normalized entities with only one prefered label per entity additional to the (sometimes interesting, so they will be available in separate facet with suffix match_ss) different entries for each occuring alias, language or synonym.

**Comment by Mandalka** [comment]
Entities (and its matching aliases) in facets are now normalized to preferred labels by the new [Open Entity Search API](https://github.com/opensemanticsearch/open-semantic-entity-search-api) entity linker by the new Open Semantic ETL plugin enhance_entity_linking
