### ISSUE TITLE
Create own facets

### ISSUE THREAD

**Issue by Johanvdberg** [opensemanticsearch/open-semantic-search#200]
Hallo

I am not sure if I ask at the correct place.

When a search is done on, the right hand side a automatic created, giving author names, places etc. I would like to create my own category. What I have done so far:

- create an ontology (not sure if this was done correctly).
- create a facet and link to the ontology (use django uri entry of the facet). 

The facet does not show after a search

**Comment by Mandalka** [comment]
Which tool did you use for creating the ontology/entity list?

The entity extraction will use RDF labels and SKOS labels as entities.

"The facet does not show after search":

The uploaded ontology will be used only if reindexing old or indexing new documents.

Or you click on "Appy ontologies" to (which if very big ontology and/or many matching documents can be CPU expensive/slow).

If you setup/map an facet (if not a facet using the ontology name will be created):

How did you setup the additional/mapped (you choosed it in setup of the ontology in the UI?) facet, by Django admin? (The facet has to be enabled for search UI, maybe only disabled if you see the values in meta data tab of documents so there are yet extracted right)?

**Comment by Johanvdberg** [comment]
My ontology could be wrong since this will be my first ontology.  I used Protege and attached [ the ontology](https://github.com/opensemanticsearch/open-semantic-search/files/3502237/words_owl.txt) where the original extension was owl.

All setting was set via the GUI and as Django admin.  The "Encryption" facet is now available. Two labels was created "DES"and "AES" with that Facet, and those strings are identified in the documents and listed under an "Encryption heading"

Can an alternative be found by to a label by using a regular expression?

**Comment by Mandalka** [comment]
I don't know if there is a standard way or property to define regular expressions by an ontology (which should be possible in a custom way, but not supported by the Ontology Manager), but Open Semantic Search / Open Semantic ETL (or Solr itself, if you setup them there) can extract Regex values from Text content to facets: https://www.opensemanticsearch.org/enhancer/regex

**Comment by Johanvdberg** [comment]
The url https://www.opensemanticsearch.org/doc/datamanagement/named_entities does not work. Where can I report it?

**Comment by Johanvdberg** [comment]
Is working :-)
