### ISSUE TITLE
django and python version problems.

### ISSUE THREAD

**Issue by Lebrero-CETEIN** [opensemanticsearch/open-semantic-search#203]
Hi everyone

I'm facing problems trying to create a new superuser to the Django Admin interface. There are some version problems between Django and python3 (all related to Django 2.0 and python3.7).

I would like to know what can I do to solve this problem. 

I'm starting to solve each problem one by one but I don't know if I will be having problems in the future when trying to use anything from the web interface, or when any back-end related task kicks on.  

Any help is well appreciated. 

Alejandro

**Comment by geraldinkorea** [comment]
I did a fresh install on Deb 10 and was able to createsuper 
I had to be sudo 
```
cd /var/lib/opensemanticsearch
sudo python3 manage.py createsuperuser
```
and there was no issue.
Really, you should probably add yourself to the groups which are created during the deb install

**Comment by Mandalka** [comment]
There is now Django 2 support in Git (master branch, support for Django 1 of current stable releases of Debian and Ubuntu in branch django1).
