### ISSUE TITLE
Move Tika processing metadata fields to tab ETL instead of Metadata

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#206]
Move Tika processing metadata fields / values like
X-Parsed-By:
org.apache.tika.parser.DefaultParser
org.apache.tika.parser.mp4.MP4Parser

X-TIKA_content_handler:
ToTextContentHandler

X-TIKA_parse_time_millis:
283

From tab Metadata to tab ETL by https://github.com/opensemanticsearch/solr-php-ui/issues/64.

**Comment by Mandalka** [comment]
Moved Tika processing status fields from Preview tab "Metadata" to tab "Import & analysis process (ETL)".
