### ISSUE TITLE
Upgrade to spaCy 2.2

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#209]

**Comment by Mandalka** [comment]
Added models nb_core_news_sm and lt_core_news_sm (which are loaded by displacy/app.py) to displacy/requirements.txt

**Comment by Mandalka** [comment]
Added new models to Open Semantic ETL config of NER models by https://github.com/opensemanticsearch/open-semantic-etl/commit/3ba6d29ade25568a746e86008b71941ca12f5d28
