### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#21]
Upgrade code and packages to Python 3, to use new features and be compatible with new Django developments.

Will solve [problems with special chars in filenames while using REST-API](https://github.com/opensemanticsearch/open-semantic-search-appliance/issues/4)

**Comment by Mandalka** [comment]
Upgraded [Django Apps to Python 3](https://github.com/opensemanticsearch/open-semantic-search-apps/issues/8)

**Comment by Mandalka** [comment]
Upgrades [ETL tools to Python 3](https://github.com/opensemanticsearch/open-semantic-etl/issues/9)
