### ISSUE TITLE
Spacy Named Entity Recognition by Spacy-Services / Displacy fails on newer installations

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#210]
Error:
500 Server Error: Internal Server Error for url: http://localhost:8080/ent

**Comment by Mandalka** [comment]
HTTP result calling http://localhost:8080/ent:

Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)

Exception by displacy/app.py:

Loading...
Loaded!
Serving on http://0.0.0.0:8080
ERROR:waitress:Exception while serving /ent
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 172, in service
    self.execute()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 440, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 289, in falcon.api.API.__call__
  File "falcon/api.py", line 286, in falcon.api.API.__call__
TypeError: process_response() takes 4 positional arguments but 5 were given

**Comment by Mandalka** [comment]
It happens because of dependency hell of the spacy-services dependency hug and its dependency of falcon (seems to be related to: https://github.com/falconry/falcon/issues/1534):

spacy-services uses dependency for hug
hug>=2.4.0,<3.0.0

Current Python package repository (pip) provides hug 2.6.0 which is dependent on falcon 2 from hug 2.5 and up.

If pinning hug to maximal 2.4.8 which is dependent on falcon 1.4 it works.

**Comment by Mandalka** [comment]
Temporary (until new releases of hug/falcon/waitress(?) on pip package repository which are fully compatible) pinned hug in displacy/requirements.txt of our package to
hug>=2.4.0,<2.5.0
instead of
hug>=2.4.0,<3.0.0

**Comment by Mandalka** [comment]
Commit: https://github.com/Mandalka/spacy-services/commit/2fa91d01292f2127ca4354b5a533c29001fe6e0f
