### ISSUE TITLE
AWS Ubuntu Server 18.04 LTS (HVM) install open-semantic-search_19.11.19.deb failed

### ISSUE THREAD

**Issue by StudyExchange** [opensemanticsearch/open-semantic-search#216]
**Env:**
System: AWS Ubuntu Server 18.04 LTS (HVM)
Python: Python 3.6.5 :: Anaconda, Inc.
Version: open-semantic-search_19.11.19.deb

**Error:**
`ubuntu@ip-172-31-14-146:~$ ls`
Anaconda3-5.2.0-Linux-x86_64.sh  anaconda3  open-semantic-search_19.11.19.deb
`ubuntu@ip-172-31-14-146:~$ python --version`
Python 3.6.5 :: Anaconda, Inc.
`ubuntu@ip-172-31-14-146:~$ sudo apt install ./open-semantic-search_19.11.19.deb `
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'open-semantic-search' instead of './open-semantic-search_19.11.19.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 open-semantic-search : Depends: php-xml (>= 0)
                        Depends: php-bcmath (>= 0) but it is not installable
                        Depends: libapache2-mod-wsgi-py3 (>= 0) but it is not installable
                        Depends: python3-rdflib (>= 0) but it is not installable
                        Depends: python3-pysolr (>= 0) but it is not installable
                        Depends: pst-utils (>= 0) but it is not installable
                        Depends: python3-celery (>= 0) but it is not installable
                        Depends: python3-nltk (>= 0) but it is not installable
                        Depends: python3-pip (>= 0) but it is not installable
                        Depends: scantailor (>= 0) but it is not installable
                        Depends: tesseract-ocr (>= 0) but it is not installable
                        Depends: tesseract-ocr-all (>= 0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Mandalka** [comment]
You have to install the dependecies of this deb package, f.e. automatically by
apt-get -f install

Maybe some versions of packages in certain OS release are not compatible anymore with used version of used API interfaces since different versions of the libraries between Debian and Ubuntu.

Having now automatic build infra for multiple OS and releases (until today checked mostly/mainly on Debian) i'll check that with newer Ubuntu releases automatically next weeks.

**Comment by StudyExchange** [comment]
OK, thank you!
