### ISSUE TITLE
Dockerfile: RUN pip3 install django-import-export error

### ISSUE THREAD

**Issue by StudyExchange** [opensemanticsearch/open-semantic-search#219]
Because of django-import-export update to 2.0 at Dec 4, 2019 according to [django-import-export history](https://pypi.org/project/django-import-export/0.2.9/#history), so this project should change `RUN pip3 install django-import-export error` to `RUN pip3 install django-import-export error==1.2.0` to aviod error `ModuleNotFoundError: No module named 'django.core.urlresolvers'`.

**Comment by StudyExchange** [comment]
Same error at deb package

**Comment by Mandalka** [comment]
Pinned to 1.2.0 by https://github.com/opensemanticsearch/open-semantic-search/commit/23a82bed1ca6f51cf6988ee61e59fab5a728be94 and https://github.com/opensemanticsearch/open-semantic-search-apps/commit/fce415a0d1e89dbf37380fe228d9db111c048481 so Debian package and Docker image should install/build correctly if django-import-export not yet on system by former installations.

**Comment by Mandalka** [comment]
To "repair" this dependencies (getting "internal server error" for search apps/web ui) after newer installation of old deb package after new release of django-import-export, use

pip3 install django-import-export==1.2.0
pip3 uninstall django

since Django was upgraded to release 3 by pip and newer release of former unpinned django-import-export and the compatible Django is yet available by its deb package.

**Comment by StudyExchange** [comment]
@saschaludwig, did you install this package sucessfully?

**Comment by saschaludwig** [comment]
> @saschaludwig, did you install this package sucessfully?

no, it seems to be completely broken on debian buster
I ended up in converting the ova file to vmware esxi and used that

**Comment by StudyExchange** [comment]
> 
> 
> > @saschaludwig, did you install this package sucessfully?
> 
> no, it seems to be completely broken on debian buster
> I ended up in converting the ova file to vmware esxi and used that

I created a new issue about package intallation error at ubuntu 16.04 https://github.com/opensemanticsearch/open-semantic-search/issues/220
