### ISSUE TITLE
Link apps for management of datasources in the UI

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#22]
So users can easy add datasources like RSS-Feeds, CSV files or index files or directories without consulting documentation or API

**Comment by Mandalka** [comment]
There is a navigation entry "Datasources" now out of the box and links to apps like RSS manager/importer or other crawlers/ingestors.

RSS manager is fully and automatically integrated by Cron job out of the box but management of feeds is done in user friendly web app/UI.

Integration of other datasource types like CSV files or planned Apps/better UIs for file path / crawl management now in own issues.
