### ISSUE TITLE
Thesaurus - not working to add Facets, Groups... in Django Admin

### ISSUE THREAD

**Issue by proteusos** [opensemanticsearch/open-semantic-search#222]
hi, i still can't get add Facets/Groups in Django Admin, or is there another way?
Is it possible to change the preconfigured groups like "Email", "Author",...??

i get this error when i add a Group in Django Admin. Before i add a Facet "test"
```

Request Method: | POST
-- | --
http://10.0.3.153/search-apps/admin/thesaurus/group/add/
1.10.7
AttributeError
'Facet' object has no attribute 'prefLabel'
/var/lib/opensemanticsearch/thesaurus/models.py in __str__, line 51
/usr/bin/python3
3.5.3

```

**Comment by Mandalka** [comment]
Saving groups in Django Admin fixed by https://github.com/opensemanticsearch/open-semantic-search-apps/commit/7807cc03903a1e16ac6051502081691b29186fed
