### ISSUE TITLE
Does not cleanly install on Debian 10

### ISSUE THREAD

**Issue by NetwarSystem** [opensemanticsearch/open-semantic-search#228]
I noticed the new release on 7/19 and created a clean Debian VM using this image.

debian-10.0.0-amd64-xfce-CD-1.iso

There are many problems, mostly to do with the Debian 10 repos not having things that are in Debian 9.9. I manually edited /etc/apt/sources.list to use the Debian 9 repos, and sort of coaxed OSS to run, but it wasn't pretty.

I returned to using Debian 9.9 and can make the system run, but it still exhibits all of the problems on install that I detailed here.

http://netwarsystem.com/2019/07/13/coaxing-open-semantic-server-into-operating-condition/

As part of the release process, someone really needs to start with a clean install of the recommended Debian version and go all the way through to make sure everything works. I can provide some assistance in testing if this would help.

**Comment by Mandalka** [comment]
I close this issue, since opened directly after release of Debian 10 and all issues should be fixed by upgrades of our packages to current Debian stable some months ago (f.e. all VMs are based on Debian 10).
