### ISSUE TITLE
Add link to tool for fuzzy search for name variants to drop down menu "Analyze" of main search ui

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#234]
Currently this usefull textmining feature by Django app "morphology" is too hidden within thesaurus manager.

**Comment by Mandalka** [comment]
Implemented main search UI link "Fuzzy search for name variants" by https://github.com/opensemanticsearch/solr-php-ui/commit/64a3cbe81716e9a579c5374b3ec16277630287d0
