### ISSUE TITLE
url of tika-server-1.22.jar is disappeared, please change to tika-server-1.23.jar

### ISSUE THREAD

**Issue by StudyExchange** [opensemanticsearch/open-semantic-search#235]
Hi,
url of https://www-eu.apache.org/dist/tika/tika-server-1.22.jar is disappeared, please change to https://www-eu.apache.org/dist/tika/tika-server-1.23.jar
I got a error when build package at my brand new AWS Ubuntu server. 
I suggest, build this repository at brand new server to check all the steps are ok, server of developers have some many cache files.

**Comment by Mandalka** [comment]
Upgraded (and now using more sustainable Apache archive url) by https://github.com/opensemanticsearch/tika-server.deb/commit/85538b18530d1e2f6990e0e84e4ed918fe18e814 and https://github.com/opensemanticsearch/open-semantic-search/commit/01a7fa533ea0f3ef10e957479f33f07215dcd418
