### ISSUE TITLE
Twitter import

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#236]
Web UI for easier [import of tweets](https://github.com/opensemanticsearch/open-semantic-etl/issues/101) without need of command line.

**Comment by Mandalka** [comment]
Implemented ETL module by https://github.com/opensemanticsearch/open-semantic-etl/issues/101

**Comment by Mandalka** [comment]
Implemented App/Web UI by new Open Semantic Search Apps Django app twitter in https://github.com/opensemanticsearch/open-semantic-search-apps/tree/master/src/twitter
