### ISSUE TITLE
Graph explorer: Server error / hanging graph visualization on click on hashtag entity

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#239]
Maybe because of incomplete URL generated in JS because of special chars.
Request Method: | GET
-- | --
http://localhost/search-apps/graph/select?fl=author_ss,tag_ss,annotation_tag_ss,person_ss,organization_ss,location_ss,email_ss,Message-From_ss,Message-To_ss,Message-CC_ss,Message-BCC_ss,hashtag_ss&limit=-1&q=%22
1.11.23
KeyError
'facet_counts'

**Comment by Mandalka** [comment]
Special chars of entity names now masked for search URLs by encodeURIComponent() so Django gets all the string before special char/anchor # too.
