### ISSUE TITLE
Create django superuser for login to admin interface

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#24]
Until automated in Open Semantic Desktop Search, you can create the superuser admin for login to the Django admin interface by following commands on command line:

cd /var/lib/opensemanticsearch
python manage.py createsuperuser

So you get a shell if using VMs:

- Open Semantic Desktop Search: open terminal and use su to get root
- Search appliance VM: Just login as root without password

**Comment by opensemanticsearch** [comment]
Added to documentation how to create a Django admin.

**Comment by Mandalka** [comment]
Implemented automatic configuration of Django super user in Open Semantic Desktop Search VM.
