### ISSUE TITLE
Automated integration tests in Docker containers

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#241]
Automated integration tests in Docker containers (which can be based on different Linux distributions and versions, so the packages can be tested for all supported distributions automatically, not only for mainly used Debian stable) so we earlier see problems
with new code and/or package releases (or/and mainly future updates of third party components)

- on other/different Linux distributions like Ubuntu

and/or

- by updates of third party pip packages (not part/available of/in Linux distribution) to incompatible or buggy python package releases which then are monitored by nightly automated integration tests, since such problems caused by dependency hell of upgrades of integrated pip packages can occur some time after development/coding (where all unit and integration tests work before/after commit/release), since mostly not caused by our at release time working code.

**Comment by opensemanticsearch** [comment]
Since in docker build the apt/dpkg option --no-install-recommends is used, we can see, if dependencies are not resolved automatically, which are installed on most standard OS installations/environments but not all (not aware of yet some dependency problems).

**Comment by Mandalka** [comment]
Added first CI/CD tests in Docker containers based on Debian and based on Ubuntu to Open Semantic ETL.

**Comment by Mandalka** [comment]
Rest of unit and integration tests of Open Semantic ETL in docker-compose environment docker-compose.etl.test.yml

**Comment by Mandalka** [comment]
First Automated End-to-end tests (f.e. integration of Solr PHP UI with Apache web server and error free compilation/integration of Open Semantic Search Apps with Apache webserver and Django) within web browser by playwright and JEST in Dockerfile-test in environment docker-compose.test.yml by test/test.js
