### ISSUE TITLE
Index filenames before full ETL

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#245]
Set default settings to index the filenames before full ETL, so files can be found, analyzed and filtered by directory names and (parts of) filenames much earlier before relatively slow ETL like text extraction and content analysis is done (which can take much time if many files), so we can use the index for getting some [ETL status info](https://github.com/opensemanticsearch/open-semantic-search/issues/155).

**Comment by Mandalka** [comment]
Changed the default plugin configs for file crawler by https://github.com/opensemanticsearch/open-semantic-etl/commit/e9f43547a26d9e08a1f0a8d13c5329665f52c8f9 and https://github.com/opensemanticsearch/open-semantic-etl/commit/158510344878a6623c09490954cb795ec944b2ae
