### ISSUE TITLE
Create my own regex doesn't work correctly

### ISSUE THREAD

**Issue by hpiedcoq** [opensemanticsearch/open-semantic-search#248]
Hello Markus,

Fresh, clean install of OSS, on Unbuntu 18.04. Deb package.

I'm trying to extract from documents some MD5 signatures.
Here is the pattern : 
`[a-f0-9]{32}$`
It matches things such as : 
```
456469e6861fe192cadbc5b4567c1a62
```
So i create a tsv file called md5.tsv containing this : 
```
#extract md5
[a-f0-9]{32}$	md5_ss
```
i appended the  /etc/opensemanticsearch/etl file like this : 
```
# Email extraction
config['regex_lists'].append('/etc/opensemanticsearch/regex/email.tsv')
config['regex_lists'].append('/etc/opensemanticsearch/regex/md5.tsv')
```
In GROUPS, I created a facet called md5_ss, with the label MD5.
![](https://framapic.org/JmcgEOYbkENN/eURg6xeKLx4v)

I created a Thesaurus/search entry called MD5, using label MD5, and Facet MD5 (no Query).
![](https://framapic.org/PBdgeVXQuknx/t9z15ITKNBnu)

The results is that I get a facet on the right called MD5, with a mention MD5, but not the MD5s themselves

![](https://framapic.org/XUNCfifiBrEl/Am7T1siNv0Cr)

I would like to see on the right, the MD5 with a digest of the x MD5 by counts, just like mails or persons.
What am I missing here?

This is what solr says when I do a query on md5_ss : 

![](https://framapic.org/7B15l5yHjfea/sYrq4NzDaJtg)

Thank you for your help.

**Comment by Mandalka** [comment]
$ defines not the end of your searched pattern/string you want to extract, but that this pattern/string you want match has to be at the end of the line/content.

You use $ after your pattern, so it only matches if your pattern occurs only exactly at end of text/line.

You might to want to use word boundaries \b by

\b[a-f0-9]{32}\b

so its not important if your pattern occurs at begin, in the middle or at the end of a content string but it has to be a separated word (else you have to work without boundaries removing \b so it matches longer words including this substrings too.

Documentation from https://docs.python.org/3/library/re.html:

\b

    Matches the empty string, but only at the beginning or end of a word. A word is defined as a sequence of word characters. Note that formally, \b is defined as the boundary between a \w and a \W character (or vice versa), or between \w and the beginning/end of the string. This means that r'\bfoo\b' matches 'foo', 'foo.', '(foo)', 'bar foo baz' but not 'foobar' or 'foo3'.


$

    Matches the end of the string or just before the newline at the end of the string, and in MULTILINE mode also matches before a newline. foo matches both ‘foo’ and ‘foobar’, while the regular expression foo$ matches only ‘foo’. More interestingly, searching for foo.$ in 'foo1\nfoo2\n' matches ‘foo2’ normally, but ‘foo1’ in MULTILINE mode; searching for a single $ in 'foo\n' will find two (empty) matches: one just before the newline, and one at the end of the string.

**Comment by Mandalka** [comment]
Warning: A thesaurus entry "MD5" will only occur in the facet, if the exact string MD5 occurs in content (which often can occur together with the regex pattern like in "My MD5 is xxx" but this thesaurus tag wont occur and be tagged if only the pattern is found in "My checksum is xxx" where the extracted checksum would be in facet md5_ss by regex but not found by thesaurus entry and so not tagged with the label "MD5".

**Comment by Mandalka** [comment]
Maybe you want to add custom config parts like
config['regex_lists'].append('/etc/opensemanticsearch/regex/md5.tsv')
to separate config file
/etc/opensemanticsearch/etl-custom
so you dont have to manage the config file /etc/opensemanticsearch/etl
manually on upgrades (which if not edited manually will automatically be overwriten/upgraded with new default settings like coming new plugins).

**Comment by hpiedcoq** [comment]
That's awesome!!! My mistake on the regex things... geez, I've been turning around during hours!!
It works like a charm.

Your hint about the etl custom file is also a brilliant idea.

Thanks for your help.
