### ISSUE TITLE
Failed task: enhance_pdf_page_preview

### ISSUE THREAD

**Issue by eliluong** [opensemanticsearch/open-semantic-search#249]
Hi, I enabled Preview Thumbnails and Segmentation to pages in configuration. On the main search page, an error on the sidebar shows up: Failed tasks while import & analysis (ETL): enhance_pdf_page_preview. I couldn't find any information to troubleshoot the error. Thanks.

**Comment by Mandalka** [comment]
Thanks for your bug report!

Error status for such issues in Search UI (filter for documents with this error by facet ETL plugins failed) in the results in Tab Preview in subtab "Import and analysis process (ETL)" in the shown field "ETL_error".

I think its something like "No access to /var/opensemanticsearch/thumbnails" which is /var/opensemanticsearch/media/thumbnails in newer releases.

So there was yet an old path setting (now separated media dir more separated from DB dir for separated docker images) in ETL plugin for single page PDF generation and apache config for providing them.

Fixed it in currently uploading Deb package, new VMs will follow tomorrow.

**Comment by languagerecipes** [comment]
This bug persists in the current Ubuntu dep package

**Comment by fractalvision** [comment]
Check that you have pdftk installed on your setup. https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/enhance_pdf_page_preview.py uses it for the generation of previews.
