### ISSUE TITLE
PDF files are being processed by Tesseract instead of extracting text

### ISSUE THREAD

**Issue by rstyczynski** [opensemanticsearch/open-semantic-search#25]
Hi, 

my pdf files are already processed by FineReader, containing text layer. Why the system uses tesseract to OCR them? How to configure OSS to just extract text, and when not possible to perform OCR? How to monitor which files are being processed by index process?

Thanks,
Ryszard

**Comment by opensemanticsearch** [comment]
Deactivate the enhance_pdf_ocr plugin by comment out the following line in /etc/opensemanticsearch/etl by setting a # at begin of the config line:

# config['plugins'].append('enhance_pdf_ocr')

If you have new Tika version, Tika will OCR again, too, so deinstall tesseract-ocr by dpkg --purge tesseract-ocr (but then OCR for images is off, too).

If you have enough CPU power, you can let tesseract work additionally to FineReader, maybe it will recognize some words better than FineReader and the other way.
