### ISSUE TITLE
Extract law codes

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#254]
Extract law codes to facets "law code", "law code clause" and "law clause" by [Open Semantic ETL plugin enhance_extract_law](https://github.com/opensemanticsearch/open-semantic-etl/issues/123)

**Comment by Mandalka** [comment]
Implemented extraction of law clauses by new ETL plugin enhance_extract_law

Todo: Add facets to facet config and ontology of law codes to ontology manager / entity search api.

**Comment by Mandalka** [comment]
Preconfigured law facets and code of law ontology (export from Wikidata) to Open Semantic Search Apps.
