### ISSUE TITLE
Use OCR cache out of the box

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#255]
Make usage of OCR cache default setting out of the box

**Comment by Mandalka** [comment]
Additional to existing OCR cache functionality for scans/images in PDFs it should cache the OCR of images by Apache Tika-Server, too.

Therefore i am working on a tesseract wrapper in https://github.com/opensemanticsearch/tesseract-ocr-cache

**Comment by Mandalka** [comment]
Migrated caching of OCR by ETL plugins to new lib https://github.com/opensemanticsearch/tesseract-ocr-cache and enabled in ETL config.

**Comment by Mandalka** [comment]
Plugin for Text Extraction by Tika-Server now can use OCR cache, too.
