### ISSUE TITLE
UI: Status info of yet not processed OCR tasks

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#256]
If OCR is configured to be processed in later stage:

Since with https://github.com/opensemanticsearch/open-semantic-etl/issues/116 after text extraction with Tika we have info about count of documents with yet open OCR tasks:

Like status info in search UI for yet not processed files add separated status/count of yet not OCRed documents.

**Comment by Mandalka** [comment]
Search UI now shows count of documents with open OCR tasks, too.
