### ISSUE TITLE
Customize Spacy NER

### ISSUE THREAD

**Issue by vidhi17** [opensemanticsearch/open-semantic-search#262]
We are trying to customize spacy ner to recognize custom entities other than Person, Locations, Organizations. For that, we have a python script that will recognize new entities. We executed that script and a new model is getting generated. But the newly indexed documents are not recognizing the custom entities. So we're unable to figure out how to integrate that model with the existing model that spacy plugin is using. How to make it recognize the custom entities? 

Any help on this will be highly appreciated.  
Thanks.

**Comment by Mandalka** [comment]
You can set the Spacy model in /etc/opensemanticsearch/etl global for all documents and/or for document languages by spacy_ner_classifier_default or/and spacy_ner_classifiers.

Then you have to config facet mappings in option config['spacy_ner_mapping'] and to add the mapped new facets (use suffix _ss for type strings) to the facets config by Django admin UI
http://localhost/search-apps/admin/thesaurus/facet/

The current default mappings (which you can reset in f.e. in /etc/opensemanticsearch/etl-custom) are:

config['spacy_ner_mapping']= {
                'ORG': 'organization_ss',
                'NORP': 'organization_ss',
                'PER': 'person_ss',
                'PERSON': 'person_ss',
                'GPE': 'location_ss',
                'LOC': 'location_ss',
                'FACILITY': 'location_ss',
                'PRODUCT': 'product_ss',
                'EVENT': 'event_ss',
                'LAW': 'law_ss',
                'DATE': 'date_ss',
                'TIME': 'time_ss',
                'MONEY': 'money_ss',
                'WORK_OF_ART': 'work_of_art_ss',
            }

**Comment by Mandalka** [comment]
And i forgot: new models if not the default spacy model names have to be added to our fork of spacy-services (which isn't yet configurable)

**Comment by Mandalka** [comment]
Since in next relase by https://github.com/opensemanticsearch/open-semantic-search/issues/301 the models are loaded dynamically, you don't have to fork and change the spacy-services code anymore, so change config is enough, if you want to use own/alternate (but without code change not an additional to original) model for documents of a language.

**Comment by ptamas88** [comment]
hello @Mandalka 
can you explain in which file can I find the config['spacy_ner_mapping'] setting?
thanks.
