### ISSUE TITLE
Installation failed by tika download timeout, can be fixed by put tika into installation package

### ISSUE THREAD

**Issue by StudyExchange** [opensemanticsearch/open-semantic-search#264]
Installation failed by download tika timeout at **China**, it will be fixed by put tika into installation package. Current version is **open-semantic-search_20.01.17.deb (~400 MB)**.

**Comment by Mandalka** [comment]
Tika Server and Solr are inside the package for a while.

So closing this issue (even if the main problem can occur again for all the python packages which are installed by pip and mainly the GBs of spaCy ml models which are downloaded by the installer).
