### ISSUE TITLE
Crawl website

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#29]
If enough time or donations, extend ETL web page indexing UI to a lightweight crawler for indexing a whole website/intranet instead of only the (initial) webpage, so no additional installation&configuration of web crawler neccesary anymore.

- Option deepness how deep to follow links.
- Bandwith / max frequency options
- Use Robots config of website

**Comment by opensemanticsearch** [comment]
Customer ordered [indexing full website by sitemap.xml](https://github.com/opensemanticsearch/open-semantic-search/issues/49)

**Comment by Mandalka** [comment]
Indexing a full website by sitemap.xml now implemented in command line ETL tool opensemanticsearch-index-sitemap.

For easier configuration/management of XML sitemaps i extended the "datasources" web UI for websites with the new tab "Sitemap".

**Comment by Mandalka** [comment]
Since open source, very powerful, implemented managment/prevention of loops and many bandwith management options, considering integration of / using [Scrapy](https://scrapy.org) as default web crawler, which could add a task for etl_web for the downloaded file.

**Comment by ripgith** [comment]
That'd be great - using scrapy. I don't remember if it can follow javascript or not. - perhaps via splash Many pages are generated using js. Another good web crawler (open source) is HTTrack.

**Comment by Mandalka** [comment]
A first beta is available as etl_web_crawl.py integrating Scrapy for crawling of full websites.

Todo: Integration with datasources web UI.

**Comment by Mandalka** [comment]
Implemented datasources web UI for crawling full websites (paths or domain) by Scrapy
