### ISSUE TITLE
Can't build the docker version - no Dockefile in some submodules

### ISSUE THREAD

**Issue by hpiedcoq** [opensemanticsearch/open-semantic-search#290]
Hello,

I'd like to build the docker version of OSS for migration purposes.
It doesn't work.

- docker build /. works like a charm
- docker build ./src/open-semantic-etl too

But for the rest, docker doesn'seem to find a Dockefile for the submodules/

Any hint?

**Comment by vaibhav-s** [comment]
The following two instructions should be removed from Readme because Docker-Compose file is automatically pulling these images from registry.

docker build ./src/solr.deb
docker build ./src/spacy-services.deb

**Comment by vaibhav-s** [comment]
Having similar issue. Did you find any fix?

**Comment by hpiedcoq** [comment]
nope... :/

**Comment by Mandalka** [comment]
Missing Dockerfile for Solr: Forgot to push some old commits from local Solr repo to github (done now).

Missing Dockerfile for Spacy services: Before you can build, you need to setup manually some dependencies in build environment like described in readme. Will change that next days for new release to fully automatic resolution of this dependencies by config as git submodule and then close this ticket.

**Comment by Mandalka** [comment]
Yet another dependency hell / debian stable dinosaur issue to solve to be able to use current main branch instead of branch django1 for build will hopefully be solved soon by https://github.com/opensemanticsearch/open-semantic-search/issues/303

**Comment by Mandalka** [comment]
Thinking about separated branch(es) for future developments so the master branch is always the stable release and not developing users can easier use the code repo and do not have to manage branches/tags.

**Comment by Mandalka** [comment]
Closing old issue, since thanks to some contributors and docker environment modernization by https://github.com/opensemanticsearch/open-semantic-search/issues/390 most components are upgraded / up to date and docker-compose build doesn't fail.
