### ISSUE TITLE
Language specifc packages

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#3]
Since features like stemming, OCR and Entity Recognition are language specific, provide fully preconfigured packages for german, so no further configuration of Solr Schema and ETL config will be needed.

**Comment by rgrativol** [comment]
Please, how do I configure the language for Portuguese? There is only English available in my version.

**Comment by Mandalka** [comment]
At the moment you can only configure the grammar (stemming) while indexing/searching to Portuguese like described in https://opensemanticsearch.org/doc/admin/config/stemming ...

Therefore search for "Portuguese" in /var/solr/data/core1/conf/managed-schema to find out the suffix for your language, which has to be configured for the fields described in previous link / documentation.

Maybe in future this config will be available via web interface or the indexing and search will be multilingual.

If you want to switch the user interface to another language than English or German, you have to translate an PO language file for that (which can be made available on github and get part of the software & distribution).

**Comment by rgrativol** [comment]
Ok. Thanks!

**Comment by opensemanticsearch** [comment]
With support of multilingual search stemming for multiple languages is configured out of the box and works, if the language of document is autodetected correct by Apache OpenNLP in Apache Tika.

So instead of language specific packages we need only an web ui to set forced languages for stemming (if not correct autodetected language to force analysis/stemming by language(s)).

**Comment by opensemanticsearch** [comment]
Web UI for configuration of languages will be implemented in https://github.com/opensemanticsearch/open-semantic-search/issues/105
