### ISSUE TITLE
Dynamic loading of SpaCy NER models

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#301]
Better performance of desktop search start and spare much RAM by loading of SpaCy NER models on first use instead on start, so not all but only models of used languages will be loaded and in the desktop search vm this models are only loaded if indexing new documents, not only if searching while the virtual machine boot/session.

**Comment by Mandalka** [comment]
Machine learning model(s) now loaded on first demand.

So if only one or few languages (of so far a dozen, and maybe more in future) are used it spares ~1 GB RAM.
