### ISSUE TITLE
Ubuntu package

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#304]
Separate package for Ubuntu, since in contrast to Debian stable Ubuntu LTS upgraded to Django 2

**Comment by Mandalka** [comment]
Removed dependency to scantailor, which is not part of Ubuntu LTS and future Debian releases anymore.

**Comment by Mandalka** [comment]
Separated (Debian package from django1 branch) Ubuntu Package from master branch (Django 2) available for download.
