### ISSUE TITLE
Cannot Build docker Image

### ISSUE THREAD

**Issue by Ierezell** [opensemanticsearch/open-semantic-search#305]
Hi, 

First thanks a lot for this software that looks really nice ! 

I wanted to use the docker image instead of installing all the virtualizing stuff....

So I cloned the repo, read the instructions and run `docker build ./` 

At Step 5/49 I got an error : 
```
COPY ./src/tika-python/tika /usr/lib/python3/dist-packages/tika
COPY failed: stat /var/lib/docker/tmp/docker-builder091119196/src/tika-python/tika: no such file or directory
```

is it a file in the .dockerignore and thus cannot copy ? I tried to clean build again `docker build --no-cache ./` without sucess... 

I'm on  : 
* Archlinux kernel zen 5.8.14
* Docker version 19.03.13-ce, build 4484c46d9d

Thanks in advance

**Comment by Mandalka** [comment]
You have to clone the git repository recursive, so the submodules (and their submodules...) will be cloned, too.

But maybe yet some problems next days (first upgrade-issues of the docker container detected by additional automated integration tests) due heavy upgrade works and restructure / improvement of CI/CD.
