### ISSUE TITLE
Cannot Clone the repository for building in docker because of missing files

### ISSUE THREAD

**Issue by ByUnal** [opensemanticsearch/open-semantic-search#306]
There are missing files in src/ 
So I cannot clone the whole repository for building on Docker.
Apparently, There are issues for Building on Docker. 
Are there anyone to solve this can help me ?

![Screenshot from 2020-10-19 17-50-12](https://user-images.githubusercontent.com/43930582/96467504-a83af400-1233-11eb-951e-df8236f67793.png)

**Comment by Mandalka** [comment]
I am working on update of docs (the repos have to be cloned recursive because of dependecies by submodules) and more CI/CD this week.

**Comment by ByUnal** [comment]
Yes, I cloned recursively, but I confronted this missing file failure. So, I hope it will be fixed too. 
I'm looking forward to new update !

**Comment by ByUnal** [comment]
I'm Waiting new doc and CI/CD update for solution of this kind of issues
