### ISSUE TITLE
Twitter Scraper doesn't work in Open Semantic Search Desktop App

### ISSUE THREAD

**Issue by ByUnal** [opensemanticsearch/open-semantic-search#307]
Even if I entered different username and tags, task is succeeded but no data return. Could be there any problem about Twitter API or something else ?

Anyone can help me ?

![image](https://user-images.githubusercontent.com/43930582/96553480-e0871480-12bd-11eb-9590-a172313dc30d.png)

**Comment by hpiedcoq** [comment]
OSS uses Twint to retrieve tweets. but Twint is now broken due to recent changes in Twitter's endpoint.

**Comment by hpiedcoq** [comment]
You can circumvent this problem by using Nitter, a twitter client that generates a RSS feed of your search : 
- by using a public instance of nitter 
https://nitter.42l.fr/search/rss?f=tweets&q=%22cve+2020-16938%22
- by hosting your personal instance of nitter.

**Comment by ByUnal** [comment]
The problem occurs due to recent changes in Twitter's endpoint. There is an suggestion above for this problem
