### ISSUE TITLE
Docker-compose: Pulling tika (opensemanticsearch/tika-server:) fails

### ISSUE THREAD

**Issue by certrik** [opensemanticsearch/open-semantic-search#311]
After cloning the repository with `git clone --recurse-submodules -j8 git://github.com/opensemanticsearch/open-semantic-search.git` and executing `docker-compose up` from `/open-semantic-search` I get ...
```
Pulling tika (opensemanticsearch/tika-server:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling tika (opensemanticsearch/tika-server:)...
ERROR: pull access denied for opensemanticsearch/tika-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

even if logged in with docker.

**Comment by Mandalka** [comment]
The docker container is in Repo tika-server.deb. I am updating docs and CI/CD these days, so resolution of such dependencies should work automatic after that.

**Comment by certrik** [comment]
@Mandalka just to let you know ... Same problem with opensemanticsearch/spacy-services . THX.

**Comment by Mandalka** [comment]
Should be solved automatically / no manual build/installation of dependencies anymore) by https://github.com/opensemanticsearch/open-semantic-search/issues/314 - if not reopen.

But i recommend to wait some days before retry/work on things, since currently all under heavy development/restructure build process to more platform independent CI/CD.

**Comment by Kkkassini** [comment]
Still getting the error with docker-compose up --build
```
Pulling tika (opensemanticsearch/tika-server:)...
ERROR: pull access denied for opensemanticsearch/tika-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
