### ISSUE TITLE
Config to build all needed docker containers by one command

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#314]
Since for automatic resolution of git dependencies all git repos / modules of Open Semantic Search like Open Semantic ETL are configured as git submodules we can configure a docker-compose.yml of this repo/direcotry structures, too, so all our Docker images can be build with one single "docker-compose build" command.

**Comment by Mandalka** [comment]
Extended docker-compose.yml of Open Semantic Search repo with build options for all git submodules / subservices.
