### ISSUE TITLE
django.core.urlresolvers is deprecated

### ISSUE THREAD

**Issue by MKatereggaExigent** [opensemanticsearch/open-semantic-search#315]
I just noticed during installation on a Debian server that the django module `django.core.urlresolvers` is one of the dependencies yet it is deprecated and replaced by `django.urls`. That can be fixed in `var/lib/opensemanticsearch/thesaurus/models.py` afterwards but is there a way to fix this in the `.deb` file before the installation?

**Comment by Mandalka** [comment]
Since in new Debian 10.6 there is a new Django version where we can finally use the code, which was migrated to Django 2 (so no separated branch/package for Debian/Ubuntu anymore), this deprecated parts should be removed and no warning in new package tomorrow.
