### ISSUE TITLE
Solr.deb submodule points to wrong commit leading to fail in docker-compose build

### ISSUE THREAD

**Issue by kevung** [opensemanticsearch/open-semantic-search#317]
When executing
```
git clone --recurse-submodules git@github.com:opensemanticsearch/open-semantic-search.git
```
there are no Dockerfile in `./src/solr.deb` leading to a failure when `docker-compose build`.

The `src` folder on the github repo ( https://github.com/opensemanticsearch/open-semantic-search/tree/master/src ) indicates that
solr.deb is pulled with commit 976cf77 which contain no Dockerfile. However, the latter is introduced in commit  8bba7eaced3c50ccc0b690604fc1adeebd1afcf2.

Thanks for your work and take care.

**Comment by Mandalka** [comment]
Updated the reference.

Tnx and sorry, last and next days under heavy restrucuring for improvement of/by CI/CD, which should prevent such issues in future.
