### ISSUE TITLE
Does not find OCR text if config option "Do OCR later" and OCR by Tika disabled

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#322]
Problem exists too for option/feature "descew" by scantailor, if done in later stage by "Do OCR later".

Problem was in default config in the time between after introdution of "Do ocr later" as default and before introdution of OCR by Tika as dedault

This happens because Plugins are not sorted by dependencies if configured/added by parameter (f.e. for doing ocr in later stage) instead of config file.

**Comment by Mandalka** [comment]
Plugin config by parameter instead of config file now sorted by dependencies, too, so ocr is done before copying data to (multilingual) default search field(s).
