### ISSUE TITLE
Starting open-semantic-search

### ISSUE THREAD

**Issue by MKatereggaExigent** [opensemanticsearch/open-semantic-search#328]
Hi, 

This might not be an issue but I need guidance on how to access the tool via `http://my_server_ip:my_port` in a browser after installation on a Debian 10 Buster server.

I have edited the config `/etc/opensemanticsearch-django-webapps/apache.conf` from `127.0.0.1` to `my_server_ip` and restart my `apache2 server` but now I don't know what next.

**Comment by Mandalka** [comment]
You should be able to reach http://my_server_ip/search out of the box, since Solr PHP UI and the Django apps are installed into the apache2 environment as /search (Solr PHP UI) and as /search-apps (Python/Django).

The config file part you mentioned is only active if you setup a http password (if clauses for htpasswd password file)

**Comment by MKatereggaExigent** [comment]
In Google, I get a `This site can't be reached` when I browse ` http://my_server_ip/search`

**Comment by Mandalka** [comment]
my_server_ip is just an example domain. You have to use your own (sub)domain which is configured for the server or IP of the server you installed it on. F.e. if the server ip is 192.168.1.1 the URL is http://192.168.1.1/search

**Comment by MKatereggaExigent** [comment]
Yes, I do understand that. I just used my_server_ip to keep my ip anonymous. Moreover, I followed the installation guidelines successfully:

`
Download the packages and modules you want to use
Get admin or super user (root)
su
Install the packages:
dpkg --install open-semantic-search-server*.deb
Install the dependencies:
apt-get -f install
`

**Comment by MKatereggaExigent** [comment]
@Mandalka  I tried running `ss -nltp` and clearly open-semantic-search is not running on any port - not even `port 80`. Meanwhile my `apache2 server` is running fine.

**Comment by aandis** [comment]
+1
