### ISSUE TITLE
Docker images don't build properly

### ISSUE THREAD

**Issue by ByUnal** [opensemanticsearch/open-semantic-search#329]
After I'm building debian package, I entered docker-compose build command. But, after a while, It threw me this.
![image](https://user-images.githubusercontent.com/43930582/97965922-25d23880-1dcc-11eb-91c2-3925440ea3ef.png)

I thought Docker problems exist no more ?? Can you help me out this one ?

**Comment by ByUnal** [comment]
Maybe It solved above problem, but still we couldn't build debian package and docker images properly. There are still missing files

**Comment by Mandalka** [comment]
Closing old issue, since neo4j not part of deb package anymore and thanks to some contributors and docker environment modernization in #390 most components are upgraded / up to date and docker build doesn't fail.
