### ISSUE TITLE
No content on indexed files.

### ISSUE THREAD

**Issue by tijlatoui** [opensemanticsearch/open-semantic-search#336]
Hello,

We are using opensemanticsearch to index files. But we don't get any content in our browser on the /search page.

Does anybody have some information for us?

This is the command we used to index our files:
`opensemanticsearch-index-dir .`
This directory contains a pdf and a txt file.

We get some information on the webpage,
![image](https://user-images.githubusercontent.com/36887685/102095214-8c169600-3e23-11eb-9b81-a59a8d1d2701.png)

When we click on content, we don't get any content from these files.
![image](https://user-images.githubusercontent.com/36887685/102095343-b6685380-3e23-11eb-9792-721656595a6e.png)

Can somebody help us?

**Comment by NetwarSystem** [comment]
You are saying that you have a directory on your system that contains one pdf and one text file.

You configured OSS to index it and based on the screen shot it appears to have done so.

You are now trying to click the link in the OSS interface and view the file, but nothing appears.

Is this a good description of the problem?

**Comment by tijlatoui** [comment]
> You are saying that you have a directory on your system that contains one pdf and one text file.
> 
> You configured OSS to index it and based on the screen shot it appears to have done so.
> 
> You are now trying to click the link in the OSS interface and view the file, but nothing appears.
> 
> Is this a good description of the problem?

Yes, this is our problem

**Comment by NetwarSystem** [comment]
What is the path for the files that are being indexed?

What path does the OSS interface show when you hover over a link?

Are the indexed files on the system where you seek to access them?

Is this being done with the workstation or the appliance version?

**Comment by Mandalka** [comment]
This happened because the user opensemanticetl has not the rights to read the files, so most plugins like text extraction and so on fail.
