### ISSUE TITLE
Preconfigured synonyms out of the box

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#35]
Integrate Open Data with synonyms, so you can find more out of the box.

**Comment by Mandalka** [comment]
For english:
- Wiktionary
- Wordnet
Wornet can be used fast and very easy by
- configure Wordnet in linked data format in thesaurus manager
- or export to Solr synonyms file by a small Python script using the Python NLTK module for wordnet.

Source for german synonyms since licence free:
Wiktionary

**Comment by Mandalka** [comment]
Make search for synonyms optional for the end users by easy to use [option in UI](https://github.com/opensemanticsearch/solr-php-ui/issues/10)

**Comment by Mandalka** [comment]
Since the new Lucene & Solr releases support multi term synonyms now, we now can [implement to use the alternate labels, aliases, synonyms and hidden labels / misspellings not only for faceted search but for full text search, too by integration with / export them to synonyms config in the Solr index](https://github.com/opensemanticsearch/open-semantic-search/issues/4).

**Comment by Mandalka** [comment]
Export of aliases from ontologies and thesauri in ontologies manager to Solr synonyms config done.
Support for multi word synonyms in search UI done.

**Comment by Mandalka** [comment]
Search and highlighting in snippets now finds/shows synoynms and aliases from thesaurus manager and ontologies out of the box.

Option to disable this in "Advanced search" and "search options"

**Comment by opensemanticsearch** [comment]
Integration of open data of irregular verbs and synonyms out of the box funded and planned to be implemented in 2018.

**Comment by Mandalka** [comment]
Decided to use Wikidata lexemes as knowledge base.

Solr Synonyms config tool to import lexemes from Wikidata implemented in https://github.com/opensemanticsearch/lexemes

Integration in web admin/config ui in tab "languages" by https://github.com/opensemanticsearch/open-semantic-search-apps/issues/41.
