### ISSUE TITLE
Build Deb Script Expects Neo4J but not in git modules

### ISSUE THREAD

**Issue by andreicozma1** [opensemanticsearch/open-semantic-search#355]
The Neo4J repository is not cloned or added to git submodules.
If cloning manually the cp and mv commands fail, not building correctly.

**Comment by Mandalka** [comment]
Removed to manage a neo4j installation for/by build of deb package.
If yet problems with build-deb please write again, maybe a missing dependency (i'll add more info in README.md when making a docker image for build-deb).
