### ISSUE TITLE
build image and run happen error

### ISSUE THREAD

**Issue by NeekHua** [opensemanticsearch/open-semantic-search#359]
when run open-semantic-search-app image happen error.Error information is following:

Action '-D FOREGROUND' failed.
The Apache error log may have more information
AH00526: Syntax error on line 1 of /etc/apache2/conf-enabled/opensemanticsearch-django-webapps.conf:
Invalid command '../conf-available/opensemanticsearch-django-webapps.conf', perhaps misspelled or defined by a module not included in the server configuration

What should  I do?

**Comment by alexander-friedrich** [comment]
@NeekHua I have exactly the same problem, so since you closed the issue I assume you found a solution; if so, it would be fantastic if you could share your fix/solution that worked for you here.
