### ISSUE TITLE
Query segmenter to a microservice or Python

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#36]
Migrate the query segmenter/query enrichment which allows to combine stemming and * operator within a single query and for options like synonyms from solr-php-ui which to Python or a micro service so it can be used in the Python / Django / open-semantic-search-apps  environment, too

**Comment by opensemanticsearch** [comment]
Test if we can drop our custom query segmenter for combining stemming and * by using multi field search by qf parameter.

**Comment by Mandalka** [comment]
No need for deleted query segmenter to seperate query fields anymore, since now using edismax which can query multiple fields at once.
