### ISSUE TITLE
Error visualize graph explorer.

### ISSUE THREAD

**Issue by nathi3** [opensemanticsearch/open-semantic-search#362]
Hi, I installed Open Semantic Desktop Search by following instructions from this document.
(Reference: https://www.opensemanticsearch.org/doc/admin/install/desktop_search)

I want to get graph visualization to work. I got the same problem as this issue, but the different error shows in the console part (Mentions issue: https://github.com/opensemanticsearch/open-semantic-search/issues/129#issuecomment-426931038)

![error](https://user-images.githubusercontent.com/91816487/135740248-e5bb8ea6-1c42-4636-992b-11ef8b312a2d.PNG)

I would be appreciated if anyone could help me solve this problem
Thanks for your attention. I’m looking forward to your reply.

**Comment by dsottimano** [comment]
Same issue and it took me a while, but here's how I fixed it from the VM image:

Create a new admin user in Debian, switch to it.

Open  /var/lib/opensemanticsearch/visual_graph_explorer/templates/graph.html in the text editor (same as `https://github.com/opensemanticsearch/open-semantic-visual-graph-explorer/blob/master/src/visual_graph_explorer/templates/graph.html`)

Change the jquery script and foundation script calls to CDNs.  Easy fix is to delete line 16 and 21 and replace with:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.7.4/js/foundation.min.js" integrity="sha512-+CnEgueYRDzx2s3IIAOpZd8HeOfrSbK3loeHw0jXJODAe3eFROHpBxEsun2kU+sZCaoAA0eFJrhfVV3RGG50GA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

Refresh the browser, i.e. http://localhost/search and you should be good to go.
