### ISSUE TITLE
Upgrade to Debian 11 bullseye

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#365]
https://www.debian.org/releases/bullseye/

**Comment by Mandalka** [comment]
Upgraded Tika-Server by https://github.com/opensemanticsearch/tika-server.deb/commit/d9aaa04c344841ee406673a08a1c42d002fd420f

**Comment by Mandalka** [comment]
Upgraded Webserver environment by https://github.com/opensemanticsearch/open-semantic-search/commit/e68e9a2e526a6abd4a4a14f1989d5eaac83fe62d

**Comment by Mandalka** [comment]
Removed integration with scantailor, which is not available as Debian package anymore by https://github.com/opensemanticsearch/open-semantic-etl/issues/151

**Comment by Mandalka** [comment]
Issues because of new Celery version: #375 and https://github.com/opensemanticsearch/open-semantic-etl/issues/145
