### ISSUE TITLE
Files without any file extension

### ISSUE THREAD

**Issue by mmoossen** [opensemanticsearch/open-semantic-search#368]
Hi,
it seems i have some, 375, files without any file extension:
![image](https://user-images.githubusercontent.com/3079721/139807236-8914f431-453a-4053-874b-b01f6e1f9e1b.png)
if i select that filter, i get an error message:
![image](https://user-images.githubusercontent.com/3079721/139807458-c3fa8483-f339-402f-b26b-7b420c20ccff.png)
this is why i am opening this issue.

but i got also a question:
Any idea, how it could find out which files are these?

many thanks
Michael

**Comment by Mandalka** [comment]
By referenced commit next release will not add (empty string to) facet "File extension".
