### ISSUE TITLE
Non terminating tesseract command with opensemanticsearch-index-dir

### ISSUE THREAD

**Issue by maurizio-emmex** [opensemanticsearch/open-semantic-search#37]
I am using the Open Semantic Search Appliance VM for indexing a shared samba drive (/mnt/g) with the command:
`# opensemanticsearch-index-dir -q /mnt/g`   
After a night the command is blocked on:
`# ps auxww | grep tess`
root      4784  0.0  0.0  12728  2100 pts/6    R+   09:00   0:00 grep tess
root      6503 98.1  1.4 369904 59360 pts/4    R+   May19 1053:07 tesseract -l ita /tmp/opensemanticetl_pdf_ocr_pcdsY3/image-002-019.pbm /tmp/opensemanticetl_ocr_35c53e7cd57715bc9b76c4143f2418d5

I have terminate the 'opensemanticsearch-index-dir -q /mnt/g' command killing tesseract:
`# kill 6503`

The opensemanticsearch-index-dir command should check if the tesseract command terminate in a reasonable amount of time, if not killing it.

Regards,
Maurizio

**Comment by Mandalka** [comment]
Could reproduce hanging call subprocess in plugin enhance_ocr_pdf.py within VM.

**Comment by Mandalka** [comment]
Racing condition occurs if parallel processing, since subprocess is not threadsafe.

**Comment by Mandalka** [comment]
Hope subprocess.run() for running external tools is fork-safe so that such racing condition can not occur anymore, since parallel processing now done fully by celery using subprocesses by library multiprocessing for workers instead of the threads from library threading former used for the file connector, where subprocess.run() seems not be thread-safe yet if calling external executables.

**Comment by Mandalka** [comment]
Timeouts for hanging ETL tasks can be set now in powerful celery config.

Additionally added process ids to temp file names, so no (rare) racing condition if multiple CPUs and so while parallel processing same image in other PDF document (or same PDF document in other path) running OCR analysis/plugin for the same image at same time.
