### ISSUE TITLE
[docker] etl service fails to start with AttributeError: 'Celery' object has no attribute 'worker_main'

### ISSUE THREAD

**Issue by Dave3o3** [opensemanticsearch/open-semantic-search#375]
see: https://github.com/opensemanticsearch/open-semantic-etl/issues/145

**Comment by sdinten** [comment]
@Dave3o3 see PR by @wsldankers for a fix: https://github.com/opensemanticsearch/open-semantic-etl/pull/146

**Comment by Mandalka** [comment]
PR merged
