### ISSUE TITLE
Open Semantic Search domain is offline

### ISSUE THREAD

**Issue by NetwarSystem** [opensemanticsearch/open-semantic-search#377]
I was just sharing about this project with a friend and I find that the domain is offline:

https://opensemanticsearch.org

Hope this is nothing serious ...

**Comment by Mandalka** [comment]
Website / old CMS is down. Migrating to static site generator (Markdown based), so it will get much easier for all to extend/improve documentation by simple text edits/pull requests and docs will be available offline & backuped for/by all in the software packages & the git repos.

**Comment by Mandalka** [comment]
Migrated to static site generator and all documentation now in git repo in /docs.
