### ISSUE TITLE
It would be very nice if the facets can be closed

### ISSUE THREAD

**Issue by jplg** [opensemanticsearch/open-semantic-search#38]
When I store 1000 documents there will be about 150 authors shown and that makes it difficult to scroll all the way down for tags and content types to handle.
If I could close a facet everything could be handled from the screen I am looking at and scrolling down would not be necessary in most cases.
If (option 1) closing facets is not easy to implement then (option 2) I would like to delete the author facet but I could not find the right spot to make the change.

**Comment by Mandalka** [comment]
[Implemented](https://github.com/opensemanticsearch/solr-php-ui/commit/764098e965f72b33c8951f7299411973e9f0d978) new parameters to limit and extend count of values/filters for facets.

Config options and easy to use UI elements for that will follow.

**Comment by Mandalka** [comment]
New UI elements for showing more or less values per facet/filter now part of todays packages release.
