### ISSUE TITLE
Migrate documentation to Markdown

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#381]
Migrate documentation from CMS to Markdown based static site generator so all can easier improve/extend them by simple text edits / pull requests and they are available offline within the software packages and better integrated documentation for the different git repositories/modules.

**Comment by Mandalka** [comment]
Migrated to markdown into directory [docs](https://github.com/opensemanticsearch/open-semantic-search/tree/master/docs).
