### ISSUE TITLE
Can the content types DOCX, XLSX and PPTX be shown as Word, Excel and Powerpoint ?

### ISSUE THREAD

**Issue by jplg** [opensemanticsearch/open-semantic-search#39]
In the content type tab the old Microsoft formats are show as Word, Excel and Powerpoint, but the new formats introduced since 2007 are not as you can see in picture 1 they are called application/vnd.openformats etc.
That makes it confusing for the user who want to find his Word, Excel and Powerpoint documents.
I found config.mimetypes.php but I cannot imagine how to solve the problem so DOC and DOCX files are shown as Word, XLS and XLSX as Excel and PPT and PPTX as Powerpoint.

**Comment by Mandalka** [comment]
With new ETL plugin [enhance_contenttype_group](https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/enhance_contenttype_group.py) additional to the facet content type with special file formats there is a new facet "Contenttype Group" with general types like "Spreadsheet", "Presentation", "Audio" or "Video", which aggregates all different file formats of different software and versions.

Please write/reopen or commit, if another important content type is missing in one of this general aggregated groups.

**Comment by Mandalka** [comment]
Will [setup this new facet to search UI facet config](https://github.com/opensemanticsearch/solr-php-ui/issues/13), so this will be a standard facet out of the box.

**Comment by Mandalka** [comment]
Additionally in the facet/filter content type the DOC and DOCX files are shown as Word, XLS and XLSX as Excel and PPT and PPTX as Powerpoint.

Former formats are shown as "Word (old format)", "Powerpoint (old format)" or "Excel (old format)".
