### ISSUE TITLE
Extract amounts of money out of the box

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#399]
Additional to machine learning NER approach add ontology- and regex-based extraction of amounts of money.

**Comment by Mandalka** [comment]
Open Semantic ETL plugin: https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/enhance_extract_money.py

**Comment by Mandalka** [comment]
Todo: Ship currencies ontology (SPARQL query is in docs) with Ontology manager.
