### ISSUE TITLE
Thesaurus (SKOS)

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#4]
Enhance Named Entities Manager towards [Thesaurus Manager](http://www.opensemanticsearch.org/doc/datamanagement/thesaurus):
- Consolidate models from tagging app to use names or concepts from thesaurus manager.
- Since concepts or entities can now have relations like broader or narrower or a tree structure: Support this [taxonomies/hierarchies](https://github.com/opensemanticsearch/open-semantic-search/issues/16) in search UI for faceted search
- Use the alternate labels, aliases, synonyms and hidden labels / misspellings not only for faceted search but for full text search, too. I.e. by exporting to synonyms.txt for Solr or enrich search query
- Add UI element for choice of language for multilingual thesaurus (to set/change field "lang" in models)
- RDF/SKOS export

**Comment by Mandalka** [comment]
Migrated Named Entity Manager to Thesaurus Manager:

- Now supporting not only alternate labels (Aliases) but hidden labels, too - i.e. for managing misspellings

- Now supporting relations like links to broader concepts, narrower concepts and related concepts.

**Comment by Mandalka** [comment]
The Ontologies Manager integrating the ontologies for ontology based faceted search now supports the W3C standard Simple Knowledge Organization System (SKOS) with its labels SKOS:prefLabel, SKOS:altLabel or SKOS:hiddenLabel from SKOS thesauri, too.

**Comment by Mandalka** [comment]
Integrated the tagging app for tagging documents with thesaurus manager so no additional managment of tags necessary anymore, since tagging app now uses names or concepts from thesaurus,

**Comment by Mandalka** [comment]
Choosing of Language own item within issue [mulitilinguality](https://github.com/opensemanticsearch/open-semantic-search/issues/17)

**Comment by Mandalka** [comment]
Since not only SKOS and important feature, [taxonomies/hierarchies in search UI for faceted search](https://github.com/opensemanticsearch/open-semantic-search/issues/16) now own issue, too.

**Comment by opensemanticsearch** [comment]
Since the new Lucene & Solr releases support multi term synonyms now, we now can implement to use the alternate labels, aliases, synonyms and hidden labels / misspellings not only for faceted search but for full text search, too by integration with / export them to synonyms config in the Solr index.

**Comment by Mandalka** [comment]
Export of aliases from ontologies and thesauri in ontologies manager to Solr synonyms config done.
Support for multi word synonyms in search UI done.

**Comment by Mandalka** [comment]
Search and highlighting in snippets now finds/shows synonyms and aliases from thesaurus manager and ontologies out of the box.

UI option to disable this in "Advanced search" and "search options".
