### ISSUE TITLE
Can we store and retrieve audio media as well via the menu ?

### ISSUE THREAD

**Issue by jplg** [opensemanticsearch/open-semantic-search#40]
Articles, images and video are covered in the menu but radio not.
Would be nice if (solution 1) there is an audio button next to videos (instead of the table button for example) or if (solution 2) audio formats are stored together with video formats and the “video” button is changed to “media” button.
The formats I think of are MP3, WAV and FLAC.

**Comment by Mandalka** [comment]
New tab/filter for "Audios" and integration with HTML5 audio player if this tab active or in preview mode.

Please reopen/write if there is an audio file type which is not analyzed by Tika as content type audio/* but application/... (you see this in preview mode or as facet)
