### ISSUE TITLE
Desktop Search VM: Firefox configuration

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#408]
Change configuration of Firefox from shipping a full preconfigured user profile in home to easier automatically manageable and smaller Firefox autoconfig:

https://support.mozilla.org/en-US/kb/managing-policies-linux-desktops
https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig
https://support.mozilla.org/en-US/kb/customizing-firefox-using-policiesjson

**Comment by Mandalka** [comment]
Policy for allowing local file links: https://github.com/mozilla/policy-templates#localfilelinks

**Comment by Mandalka** [comment]
Local file links policy now provisioned independent from Firefox user profile by Firefox config https://github.com/opensemanticsearch/open-semantic-search/blob/master/src/open-semantic-desktop-search/etc/firefox/policies/policies.json
