### ISSUE TITLE
Desktop Search VM: Migrate from vmdebootstrap to Ansible playbook

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#409]
Since Debian 11 has no package of vmdebootstrap anymore, migrate the installation in the VM to an Ansible playbook.

**Comment by Mandalka** [comment]
Config files of destination system in subdirectories of [`src/open-semantic-desktop-search`](https://github.com/opensemanticsearch/open-semantic-search/tree/master/src/open-semantic-desktop-search)

**Comment by Mandalka** [comment]
Ansible Playbook: [src/open-semantic-desktop-search/playbook.yml](https://github.com/opensemanticsearch/open-semantic-search/blob/master/src/open-semantic-desktop-search/playbook.yml)

**Comment by Mandalka** [comment]
Documentation for developers: [src/open-semantic-desktop-search/README.md](https://github.com/opensemanticsearch/open-semantic-search/blob/master/src/open-semantic-desktop-search/README.md)
