### ISSUE TITLE
Desktop Search VM: Use /etc/opensemanticsearch/connector-file-custom config

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#410]
Use /etc/opensemanticsearch/connector-file-custom only with changes/custom vm settings instead of own fork of /etc/opensemanticsearch/connector-file config, so we have not to manage both on changes in main package.

**Comment by Mandalka** [comment]
Only custom ETL config parts for Desktop Search VM environment now in https://github.com/opensemanticsearch/open-semantic-search/blob/master/src/open-semantic-desktop-search/etc/opensemanticsearch/connector-files-custom
