### ISSUE TITLE
task queue management

### ISSUE THREAD

**Issue by samoal** [opensemanticsearch/open-semantic-search#412]
Is queue management by celery enabled by default?
How to start or configure it?
How to get flower monitoring website working?

**Comment by opensemanticsearch** [comment]
Will add it to deb package and docker containers out of the box (currently by default only in Desktop Search VM)

**Comment by Mandalka** [comment]
Added flower setup to the deb package.

**Comment by Mandalka** [comment]
Added and linked admin documentation for task queue management in [/docs/doc/admin/queue](https://github.com/opensemanticsearch/open-semantic-search/tree/master/docs/doc/admin/queue)

**Comment by Mandalka** [comment]
Flower now integrated in the docker environment, too.
