### ISSUE TITLE
AttributeError 'Group' object has no attribute 'title'

### ISSUE THREAD

**Issue by urosch** [opensemanticsearch/open-semantic-search#414]
AttributeError
'Group' object has no attribute 'title'

![image](https://user-images.githubusercontent.com/10198214/117251022-5f036800-ae44-11eb-9138-605620784c7a.png)

_Originally posted by @chrbratt in https://github.com/opensemanticsearch/open-semantic-search/issues/339#issuecomment-833261123_

**Comment by urosch** [comment]
Request Method:	POST
Request URL:	http://url-something.com/search-apps/admin/thesaurus/group/add/
Django Version:	2.2.25
Exception Type:	AttributeError
Exception Value:	'Group' object has no attribute 'title'
Exception Location:	/var/lib/opensemanticsearch/thesaurus/models.py in __str__, line 49
Python Executable:	/usr/bin/python3
Python Version:	3.9.


var/lib/opensemanticsearch/thesaurus/models.py in __str__
49. 		return self.title …

▼ Local vars
Variable	Value
self	Error in formatting: AttributeError: 'Group' object has no attribute 'title

**Comment by urosch** [comment]
I've got a similar (at least how it manifests) problem using the "group manager" in the django admin interface. Trying to add a group results in the same exception

> AttributeError at /admin/thesaurus/group/add/

> 'Group' object has no attribute 'title'

_Originally posted by @schneipk in https://github.com/opensemanticsearch/open-semantic-search/issues/339#issuecomment-799513288_

**Comment by Mandalka** [comment]
Thanks for bug report (but this thesaurus "Groups" are not Regex groups (linked ticket i'll answer/link documentation there).
