### ISSUE TITLE
use external indices

### ISSUE THREAD

**Issue by trenkert** [opensemanticsearch/open-semantic-search#43]
Is it possible for opensemanticsearch to use data from external indices like xapian, nepomuk, or zeitgeist? Many users already use apps like recoll, gnome tracker, or others that build their own fulltext database. It would be great if open semantic seach could include this data into its search results. 

Especially with apps like zeitgeist that use temporal semantic aspects to group files and documents.

**Comment by Mandalka** [comment]
Sorry, it uses only one main Solr index (which can be distributed on different/multiple servers by Solr cloud), but it is not a distributed search engine and i have no time to add ETL connectors to import such data, since other issues more important.
