### ISSUE TITLE
Upgrade to Debian 9 (Stretch)

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#44]
Build/upgrade packages for/to new Debian stable release

**Comment by Mandalka** [comment]
Solr package upgraded to Debian 9 Strech

**Comment by Mandalka** [comment]
[Solr-PHP-UI package upgraded to Debian 9 Strech](https://github.com/opensemanticsearch/solr-php-ui/issues/11)

**Comment by Mandalka** [comment]
Upgraded [now Python 3 based ETL package](https://github.com/opensemanticsearch/open-semantic-etl/issues/9) ready for Debian 9 Strech

**Comment by Mandalka** [comment]
Upgraded now [Python 3 based Search Apps package](https://github.com/opensemanticsearch/open-semantic-search-apps/issues/8) ready for Debian 9 Strech

**Comment by Mandalka** [comment]
All in one package and its dependencies for Debian and Ubuntu now upgraded to Python 3 and Debian 9 Etch.

**Comment by Mandalka** [comment]
Added [DB migrations](https://github.com/opensemanticsearch/open-semantic-search-apps/issues/12), so Debian package now working out of the box / automatic initialization of DB on Debian 9, too, since new Django migrate is doing DB migrations only if explicit migrations for apps there.

**Comment by Mandalka** [comment]
Migrated VM build of Open Semantic Search Appliance to Debian 9 Stretch and Python 3, so Open Semantic Search Appliance can be build automatically based on new and future versions of Open Semantic Search Server.

**Comment by Mandalka** [comment]
With Migration of Gnome & Firefox settings for Open Semantic Desktop Search VM to Debian 9 stretch all packages or VMs based on current Debian stable release.
