### ISSUE TITLE
Fix installation/docker build issues (Django issues)

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#443]
Seems the installation of the current django import export version has meanwhile dependency to higher django version which is automatically installed additionally to the django deb package (and the search apps not compatible yet).

Remove or pin version of django import export extension.

**Comment by Mandalka** [comment]
Removed Django extension django-import-export.

Building docker images seems to work again.

New deb package is available for download.

Feel free to reopen, if yet issues with this.
