### ISSUE TITLE
wrong dependency to mod_wsgi for ubuntu 16.04 package

### ISSUE THREAD

**Issue by lunatic4ever** [opensemanticsearch/open-semantic-search#45]
I have downloaded this deb file 
https://www.opensemanticsearch.org/download/open-semantic-search_17.07.03.deb
I'm running ubuntu server 16.04.2

The django apps are not working because there is a dependency to libapache2-mod-wsgi but since you are upgrading to python3 it should be libapache2-mod-wsgi-py3

also had to add a line to the settings file because otherwise some modules are not found
sys.path.append("/usr/lib/python3/dist-packages") 

Keep up the good work!

**Comment by adrienc921** [comment]
Hi, I have exactly the same issue :( The whole app. is using python 2 with apache but the dependencies are compiled under python 3. 

@lunatic4ever did you manage to make it work using the sys path?

Thanks for the app it looks amazing.

**Comment by Mandalka** [comment]
There was an old (Python 2) based dependency like described below, it's changed to Python 3 based libapache2-mod-wsgi-py3 in the all in one package now, too and the new package should be available for download within the next hours.
