### ISSUE TITLE
Index whole website by sitemap

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#49]
Index a whole website by sitemap.xml

**Comment by Mandalka** [comment]
New command line tool: opensemanticsearch-index-sitemap

**Comment by Mandalka** [comment]
Todo: Datasources web UI for easier configuration and management of sitemaps.

**Comment by Mandalka** [comment]
Implemented datasources web UI for easier configuration and management of sitemaps.
