### ISSUE TITLE
Recommender for thesaurus for easy adding of alternate labels / word forms and typos / misspellings

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#5]
Recommender for easy adding alternate labels (i.e. by different stemmers) and misspellings (find by levensthein distance) to concepts in thesaurus

**Comment by opensemanticsearch** [comment]
An early test version (yet problems, if too many documents with this entity) is available.

First draft of documentation:

http://www.opensemanticsearch.org/doc/datamanagement/thesaurus/recommender

**Comment by opensemanticsearch** [comment]
The recommender will be extended for names and more documents:

- Support multi term synonyms for whole names (first and last name) / multi term labels
- Retrieve documents/highlightings in multiple steps instead of once, so more documents can be processed

**Comment by Mandalka** [comment]
Fuzzy search recommendations now for multi term labels, too by Solr Complex Phrase Query Parser.

**Comment by Mandalka** [comment]
Works now on full corpus instead of a document sample.

**Comment by Mandalka** [comment]
By using Open Semantic Entity Search API it now supports external thesaus/ontoligies, too.
