### ISSUE TITLE
setup a document search based on local files as a website

### ISSUE THREAD

**Issue by thetaung82** [opensemanticsearch/open-semantic-search#50]
/etc/opensemanticsearch/connector-files
I tried to config it but it didn't work 
config['mappings'] = { "/home/user/projects/": "http://localhost/search/projects/" }
any suggestion

**Comment by opensemanticsearch** [comment]
How is the resulting link / uri to such a document if you search/find it ?

Maybe you indexed it with a relative path like "opensemanticsearch-index-file projects", so for the mapping it is not seen as /home/user/projects ...

**Comment by thetaung82** [comment]
So I do need to do index again  opensemanticsearch-index-file  /home/user/projects
How can I reset the previous result.
URI is http://localhost/search/projects/folder/file.ext

**Comment by opensemanticsearch** [comment]
You can "reset" the index by the command line with
opensemanticsearch-delete --empty

Todo: Automatic change of relative paths to absolute paths.

**Comment by thetaung82** [comment]
I am still getting The requested URL /search/projects/ was not found on this server any idea?

**Comment by opensemanticsearch** [comment]
Does an webserver exist which delivers the URIs you link the files to? The search engine can do the mapping but will not deliver this files as an HTTP webserver. So you have to config for example your apache webserver to deliver this files/uris via HTTP, too.

Another point could be, that the index process was done by [filemonitoring](https://github.com/opensemanticsearch/open-semantic-etl/issues/18)?

**Comment by JamesTownend** [comment]
I'm experiencing a similar problem. I have indexed files in "/usr/share/solr-php-ui/documents" using the absolute path and used the following in the "connector-files" config file:

config['mappings'] = { "/usr/share/solr-php-ui/documents/": "http://localhost/search/documents/" }

but the files are linked to http://localhost/documents/file_name instead, which can't be found. I need instead to navigate manually to http://localhost/search/documents/file_name to find the file.
