### ISSUE TITLE
Cannot open files directly

### ISSUE THREAD

**Issue by PeterausMG** [opensemanticsearch/open-semantic-search#51]
I have installed <open-semantic-search_17.08.21.deb> on Ubuntu server 16.04. User  and group "solr" have been created. Warning that the home directory </var/solr> does not belong to the user who has just been created. Installation otherwise ok. 
After indexing a local directory (pdf), only the preview of a file (php-sript) works, a direct opening of the file is not possible. However, the path is displayed correctly. I can copy it and open the file in new tab. Is there a connection? Can this be solved? 
thanks in advance

**Comment by opensemanticsearch** [comment]
If the files are local files (file://... instead of http://...) this is a security function of your browser which not allows internet pages (like the search engine) to open links to local files on your harddisk.

You can set an exception for the search engine URL in your browser.

**Comment by PeterausMG** [comment]
Thanks for the quick response, it works
