### ISSUE TITLE
Removing deleted or renamed files from search index

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-search#6]
Ist there a way to notify the solr search index about removed/renamed files? They seem to stay in the index forever. Manually forcing to reindex a directory seems not to help. I am mapping the filenames from the file directory to a http URL.

**Comment by opensemanticsearch** [comment]
It is implemented in File Monitoring Remote yet, which will be the new code base for local File Monitoring, soon and affects deleted files if file monitoring is active.

A company ordered another tool for cleaning the index which iterates through the index and removes entries for files which do not exist any more. So this will affect files, too, which were deleted while file monitoring was inactive or booting / initializing on file server (which can take a while if millions of document files).

This new tool will be open sourced for new release (in two or three weeks)
