### ISSUE TITLE
Opensemanticsearch shows error at 'http://localhost/search/'

### ISSUE THREAD

**Issue by CosmicT** [opensemanticsearch/open-semantic-search#60]
I have setup opensemanticsearch following the instructions in their documentation . It was working fine untill i started receiving this error .

Error:

Apache_Solr_HttpTransportException: '400' Status: Bad Request in /usr/share/solr-php-ui/Apache/Solr/Service.php:338 Stack trace: #0 /usr/share/solr-php-ui/Apache/Solr/Service.php(1170): Apache_Solr_Service->_sendRawGet('http://localhos...') #1 /usr/share/solr-php-ui/index.php(1281): Apache_Solr_Service->search('*:*', 0, 10, Array) #2 {main}

I feel like it has nothing to do with solr . The error started showing up after a failed attempt to apply an ontology . Kindly help at your earliest .@opensemanticsearch

**Comment by Mandalka** [comment]
Maybe there is a facet for this ontology without any document tagged by that yet.

You can try to comment out the ontology / added facet in /etc/solr-php-ui/config.facets.php until the [issue](https://github.com/opensemanticsearch/open-semantic-search/issues/63) is solved.

**Comment by Mandalka** [comment]
Did you use Solr admin UI or managed schema API for editing of the managed-schema?

This will cause the fail, see anaylsis of this [closed issue](https://github.com/opensemanticsearch/open-semantic-search/issues/63).

If so, you can overwrite the corrupted managed-schema file with the original from the package and edit it manually without Solr admin UI.
