### ISSUE TITLE
SPARQL endpoint as datasource for Ontologies manager

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#62]
Config options for SPARQL endpoint and SPARQL query as datasource for navigation/analysis/facets/filters for easier management (of parts) of Ontologies like for example Wikidata without additional need to manage the download of the graph.

**Comment by Mandalka** [comment]
Implemented additional datasource option "SPARQL endpoint" in ontologies manager UI.
