### ISSUE TITLE
Search UI fails, if facet configured without documents in index using this field

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#63]
If not yet at least one document using this field in index but it is configured as facet, search UI/Solr query requesting this facet fails.

**Comment by Mandalka** [comment]
Workarround: Uncomment not yet filled facets in /etc/solr-php-ui/config.facets.php

**Comment by Mandalka** [comment]
Will try if this happens after Upgrade to Solr 7.
If so, maybe have to initialize index structure after facets config, for example by indexing an empty document with new fields and delete it after that.

Test if this happens for dynamic field names, too. If not maybe its possible to use dynamic field names for ontologies, too.
