### ISSUE TITLE
Integration of Hypothesis annotations

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/open-semantic-search#64]
Integration with [Hypothesis](https://hypothes.is) which has powerful UIs for web annotations.

**Comment by Mandalka** [comment]
Added authorization for hypothes.is to import tags and annotations that are private or in not public groups.

**Comment by Mandalka** [comment]
Added command line interface, so you can run imports of annotations by command line and/or by cron, too.

**Comment by Mandalka** [comment]
Easier configuration by Open Semantic Search Apps in datasources web UI which now includes additional setup options for configuration of Hypothesis API authorization.

**Comment by Mandalka** [comment]
Todo:

Call API by paging if more annotations than the API limit of 200 since last import.

Integration of hypothesis annotations in Solr-PHP-UI out of the box.

**Comment by Mandalka** [comment]
Added [user documentation and tutorial for integration of Hypothesis annotations, tags and documents in Open Semantic Search / Solr / Elasticsearch](https://opensemanticsearch.org/doc/datamanagement/annotation/hypothesis).

**Comment by Mandalka** [comment]
By [Hypothesis integration with Solr PHP UI commands](https://github.com/opensemanticsearch/solr-php-ui/issues/43) you can annotate visual by Hypothesis from search results and document preview even if your browser has not installed the Hypothesis plugin

**Comment by Mandalka** [comment]
The [document preview now shows Hypothesis tags & annotations in additional tab "Tags and Annotations"](https://github.com/opensemanticsearch/solr-php-ui/issues/42), so you don't have to read them in the tab "Metadata" within many other meta data.

**Comment by Mandalka** [comment]
Added Hypothesis tags facet to default / out of the box facet config of Open Semantic Search Apps.

**Comment by trenkert** [comment]
Is it possible to inlcude hypothesis as a local running container (like Docker)?

**Comment by opensemanticsearch** [comment]
It should be possible and there are settings for change the instance / REST-API URLs in Open Semantic ETL and Open Semantic Search Apps user interfaces for configuration, but installation is effort:

http://h.readthedocs.io/en/latest/developing/install/

As i can see, there are no ready Debian / Ubuntu packages or Docker containers.

If there were, i would love to use them for local installation / integration out of the box.
