### ISSUE TITLE
EML files - no index

### ISSUE THREAD

**Issue by hpiedcoq** [opensemanticsearch/open-semantic-search#69]
Hi,

I'm currently working on indexing a bunch of EML files. 
These indexation by OSS seems to be working but when I try to preview it, I just get the header (sender, receiver) and the subject. No text is indexed.

Is there any special parameter for Tika, concerning the .EML format?

Thanks!

Hervé

**Comment by Mandalka** [comment]
Thanks for your bug report.

Emails can have multiple parts so Tika outputs an array with a document and own content field for each part instead of one content field for whole file.

I'll add such subparts within next days.

**Comment by hpiedcoq** [comment]
Great! Thank you!

**Comment by Mandalka** [comment]
Subparts of files are now indexed, too by adding their content to the field(s) like content.

When time, maybe better solution by hierarchical / nested documents.

Will add more / all Tika fields like client or headers for technical analysis within next week(s).

**Comment by hpiedcoq** [comment]
Amazing work!!
Thanks for that!
