### ISSUE TITLE
Config option to set count of values for each facet/filter

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#72]
Extend admin web UI for configuration of initial count of shown values for each facet/filter, which can be extended in the search UI by clicking on "Show more".

**Comment by Mandalka** [comment]
Extended Django admin UI in open-semantic-search-apps and generation of Solr-PHP-UI config file to use this new parameters in https://github.com/opensemanticsearch/solr-php-ui/issues/17
