### ISSUE TITLE
Named Entity Recognition with Spacy out of the box

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#74]
Thanks to the new multilingual integration of SpyCy in new Open Semantic ETL Plugin enhance_ner_spycy.py the Named Entity Recognition (NER) supports additional languages.

For easier installation the integrated SpyCy libraries / textanalytics software / dependencies should be installed automatically on installation of Open Semantic Search.

**Comment by Mandalka** [comment]
Installation of spaCy plugin, libraries, dependencies and language models now automatically out of the box.

Debian and Ubuntu packages available.

Upgraded VMs will be available for download tomorrow after build and upload.
