### ISSUE TITLE
User interfaces for graph visualization parameters

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#75]
Since thanks to a client now we have [controls for count of facet values](https://github.com/opensemanticsearch/open-semantic-search/issues/38), use such parameters like [facet/properties controls](https://github.com/opensemanticsearch/solr-php-ui/issues/7) for graph analysis view, too.

Additionally there should be [controls for zoom in / out](https://github.com/opensemanticsearch/solr-php-ui/issues/22).

**Comment by Mandalka** [comment]
Now the Neo4j browser with more powerful graph analysis and graph visualization features and user interfaces can be used to analyze and explore indirect connections over multiple documents or emails by export of named entities to Neo4j graphdatabase by new [ETL plugin for Neo4j integration](https://github.com/opensemanticsearch/open-semantic-etl/issues/47).

![Neo4j graph visualization](https://user-images.githubusercontent.com/1010780/36641990-31cf18d6-1a39-11e8-9c7f-f3fbdb40bd25.png)

**Comment by Mandalka** [comment]
Zoom implemented by https://github.com/opensemanticsearch/open-semantic-visual-graph-explorer/issues/1

**Comment by Mandalka** [comment]
Graph visualization is now done by [Django app Open Semantic Visual Linked Data Graph Explorer](https://github.com/opensemanticsearch/open-semantic-visual-graph-explorer) based on Cytoscape.js.

The Solr-PHP-UI graph view has now user interfaces for parametrize the graph analysis and graph visualization by selection of entity types / classes / facets / properties and amount/limit of initial entities.

More UI elements for setting custom limits on extending node/loading more connections in https://github.com/opensemanticsearch/open-semantic-visual-graph-explorer/issues/4
