### ISSUE TITLE
crawler errors

### ISSUE THREAD

**Issue by hpiedcoq** [opensemanticsearch/open-semantic-search#76]
Hi Markus,

I've to deal with the same error on three distinct install  of OSS. When I try to update (I've tried the two versions of january), I get a Python error in both Thesaurus section : 

```
Request Method: | GET
-- | --
http://127.0.0.1/search-apps/thesaurus/create
1.11.4
OperationalError
no such column: thesaurus_facet.enabled
/usr/lib/python3/dist-packages/django/db/backends/sqlite3/base.py in execute, line 328
/usr/bin/python3
3.6.3
['/var/lib/opensemanticsearch',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3/dist-packages/opensemanticetl',  '/']
Mon, 22 Jan 2018 12:13:16 +0000
```

and crawler section : 

```

error : 

Request Method: | GET
-- | --
http://127.0.0.1/search-apps/crawler/
1.11.4
OperationalError
no such column: crawler_crawler.crawler_type
/usr/lib/python3/dist-packages/django/db/backends/sqlite3/base.py in execute, line 328
/usr/bin/python3
3.6.3
['/var/lib/opensemanticsearch',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3/dist-packages/opensemanticetl',  '/']
Mon, 22 Jan 2018 12:10:56 +0000
```

Search and indexing is still possible but not enriching.

Any hint?

Thanks!

**Comment by Mandalka** [comment]
Seems you are using a Debian or Ubuntu Linux version higher/newer than the LTS with newer Django.

So the upgrade of the Django database fails because of https://github.com/opensemanticsearch/open-semantic-search-apps/issues/18 (why i close this issue, please use the linked issue).

**Comment by Mandalka** [comment]
Migrated all settings to new Django version by patch of https://github.com/opensemanticsearch/open-semantic-search-apps/issues/18 so it should run on coming Ubuntu or Debian releases, too.
