### ISSUE TITLE
Ubuntu Packages for Ubuntu version (LTS)

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#8]
New Ubuntu 16.04 LTS version needs own seperated deb packages since they have other dependencies than Debian stable, since PHP package names and versions differ.

Thanks for bug reports and donation!

Planned for end of first week of october.

**Comment by scream88** [comment]
Is the new .deb file released? I can't find a link so far.

**Comment by opensemanticsearch** [comment]
New package for Ubuntu 16.04 LTS is integrated to automatic build system but will be available not before today or tomorrow on download site (there is a problem with uploading to new server the website moved to with HTTPS by default now).

I'll close the issue when upload is repaired and done.

**Comment by opensemanticsearch** [comment]
Ubuntu 16.04 LTS package available on public download server.

Please read the [Open Semantic Search Server installation tutorial](http://www.opensemanticsearch.org/doc/admin/install/search_server), since on Ubuntu there is an [issue with the Solr installation script](https://github.com/opensemanticsearch/solr.deb/issues/1).
