### ISSUE TITLE
New view / tab Knowledge Graph / Entities

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#81]
Add/integrate new view Named Entities to search to be able to focus search on named entities like persons or organizations instead of documents.

[Add entities from knowledge graph like persons or organizations to facets](https://github.com/opensemanticsearch/open-semantic-etl/issues/38) so entities from the Knowledge graph will be shown in view "Named Entities", too, even if not occur in documents but have RDF properties / data from the knowledge graph.

**Comment by Mandalka** [comment]
Now there is a new view/tab "Entities" so you can focus on / analyze only named entites/facets like persons, organizations, places and so, without a document list on your screen, like on list view, yet.

**Comment by Mandalka** [comment]
In view/tab "preview" for knowledge graph entities the properties/fields and references/links/values are now shown directly in first/open preview sub tab "content" instead of tab meta.

**Comment by Mandalka** [comment]
Linked data / URI references in/from RDF knowledge graph(s) are now linked as click-able weblinks with human readable labels in view preview, too, so you can easy browse and navigate the graph by this links in preview mode.

**Comment by Mandalka** [comment]
URIs of RDF knowledge graph are now linked to (pre)view / graph view of the linked entity, so we can not only find and preview but additional browse linked data within the UI.

**Comment by Mandalka** [comment]
Mapped classes from Wikidata and schema.org for persons, organizations and locations to facets, so linked data in knowledge graph using this standard URIs will be indexed, found and can be shown/filtered by same facets / entities classes like named entities recognition results from machine learning.

**Comment by Mandalka** [comment]
Since human readable labels of RDF entities with RDF classes now additionally added to (mapped) facets of the class, the entities of knowledge graph are included in the view "Named entities" and the knowledge graph entities themselves can be listed / filtered together with entities of named entity recognition by facets like persons, organizations or locations (like it is/was possible for properties/facets for linked other entities).
