### ISSUE TITLE
UI: Use labels instead of URIs for facets/fields from RDF knowledge graph

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#9]
To enable full text search, linked references (URIs) in RDF knowledge graphs are transformed to/indexed/showed by their labels/text instead of the reference URI/ID.

Similar should happen for printing facet/field/columns/property names in preview or table view for more pretty tables or preview and better readability (because RDF labels language sensitive: in custom language).

Add own preview view for type knowledge graph / RDF

**Comment by Mandalka** [comment]
Added own [view for knowledge graph in view/tab "preview"](https://github.com/opensemanticsearch/open-semantic-search/issues/81).
