### ISSUE TITLE
Open Semantic Search Server Installation fails on Ubuntu 16.04.3 LTS (Xenial Xerus)

### ISSUE THREAD

**Issue by mohitsahay** [opensemanticsearch/open-semantic-search#91]
I am trying to install Open Semantic Search Server on an AWS vm with Ubuntu 16.04.3 LTS (Xenial Xerus) by using ALL IN ONE Package: https://www.opensemanticsearch.org/download/open-semantic-search_18.02.02.deb. 

Below are some of the errors I am getting in installation traces, any help on it would be great:

_apache2_reload: Your configuration is broken. Not reloading Apache 2
apache2_reload: apache2: Syntax error on line 216 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/conf-enabled/solr-php-ui.conf: No such file or directory_

However, I checked and I can see solr-php-ui.conf in the path /etc/apache2/conf-enabled.

_ImportError: No module named 'opensemanticetl'
chown: cannot access '/var/lib/opensemanticsearch/db.sqlite3': No such file or directory
chmod: cannot access '/var/lib/opensemanticsearch/db.sqlite3': No such file or director_y

Also once the installation completes, I get 500 error on clicking effectively on all the menu items.
And in error logs of apache2, I am getting numerous wsgi:error like: 

_[Wed Feb 07 10:32:01.849612 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166] mod_wsgi (pid=10969): Target WSGI script '/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py' cannot be loaded as Python module.
[Wed Feb 07 10:32:01.849660 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166] mod_wsgi (pid=10969): Exception occurred processing WSGI script '/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py'.
[Wed Feb 07 10:32:01.849764 2018] [wsgi:error] [pid 9645] [client 127.0.0.1:38168] mod_wsgi (pid=9645): Target WSGI script '/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py' cannot be loaded as Python module.
[Wed Feb 07 10:32:01.849814 2018] [wsgi:error] [pid 9645] [client 127.0.0.1:38168] mod_wsgi (pid=9645): Exception occurred processing WSGI script '/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py'.
[Wed Feb 07 10:32:01.849817 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166] Traceback (most recent call last):
[Wed Feb 07 10:32:01.849864 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166]   File "/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py", line 14, in <module>
[Wed Feb 07 10:32:01.849870 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166]     application = get_wsgi_application()
[Wed Feb 07 10:32:01.849880 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166]   File "/usr/lib/python3/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Wed Feb 07 10:32:01.849885 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166]     django.setup()
[Wed Feb 07 10:32:01.849893 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166]   File "/usr/lib/python3/dist-packages/django/__init__.py", line 18, in setup
[Wed Feb 07 10:32:01.849898 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166]     apps.populate(settings.INSTALLED_APPS)
[Wed Feb 07 10:32:01.849907 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166]   File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 78, in populate
[Wed Feb 07 10:32:01.849911 2018] [wsgi:error] [pid 10969] [client 127.0.0.1:38166]     raise RuntimeError("populate() isn't reentrant")_

**Comment by hpiedcoq** [comment]
same here

**Comment by opensemanticsearch** [comment]
Seems to be a filesystem rights problem, since user rights not in git. Will add explicit rights setting to build/install script.

**Comment by opensemanticsearch** [comment]
The database can not be found, because import of export_solr fails, so creating DB by scripts not possible, because scripts do not compile. Check for path settings so import of relative path works.

**Comment by hpiedcoq** [comment]
great! Thanks!

**Comment by Mandalka** [comment]
Open Semantic ETL package (needed dependency) build failed on fresh git based build environment, because empty directory needed for build but not available in git. A mkdir now part of build script, so should not happen again if building from git repository on fresh build environment.
New package is available for download after upload finished in ~15 minutes, which solves the problem with the Django Apps.

**Comment by Mandalka** [comment]
To check: Apache problem seems to be a filesystem rights problem, since user rights not in git. Will add additional explicit rights setting to build script or post install script https://github.com/opensemanticsearch/solr-php-ui/blob/master/build/deb/stable/DEBIAN/postinst.

**Comment by hpiedcoq** [comment]
Works like a charm! Thank you!

**Comment by mohitsahay** [comment]
Thanks for the new patch.

One issue though, it doesn't seem to index my files contained in a directory from the UI if I go Datasources->Files & directories(filesystem)-> Index now.

However, using CLI it works smoothly for individual files. For indexing all contents of the directory, nothing happens.

**Comment by Mandalka** [comment]
I close this old ticket (a bug was fixed in the time the ticket was opened where the preconfigured file queue name was not the same like in workers config).
If this was not this bug mostly there are file rights problem (the user opensemanticetl (the user the workers run as) has no access).

You can see more in the log file /var/log/daemon.log whats (not) happening/what is the problem.

**Comment by Nichols974** [comment]
I installed Open Semantic Search on ubuntu in December 2019 and still had the same issue though. Has the bug been fixed in between?
