### ISSUE TITLE
Regex question (no bug)

### ISSUE THREAD

**Issue by hpiedcoq** [opensemanticsearch/open-semantic-search#92]
Hi,

Something that I don't get while playing around with OSS : Regex.
Suppose that I want to automatically extract Bitcoin adresses from my document set.

I've tried to add a line to the email.tsv : 

[\w\.-]+@[\w\.-]+ [tab] email_ss
^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$ [tab] bitcoin_ss

it doesn't work for me.
The Same occures when I create a personal.tsv file with my regex and add it to the config file.

Is there anything that I'm missing here? 
Thanks
Hervé

**Comment by opensemanticsearch** [comment]
I dont know much about bitcoin adresses

Aut are you sure, that not only the adress but the whole line(s) extracted from content begins with that regex (^) and ends with it ($) ?

Additional chars like whitespace on begin or end of the line would not match the regex.

**Comment by opensemanticsearch** [comment]
In which field is the adress?

Yet the analysis would be done only for content field, so if in other field, it has to be added to the fields which are analyzed by the Regex plugin.

**Comment by hpiedcoq** [comment]
OK, in order to be more precise here's a sample document.
https://framadrop.org/r/4JWpv1s7hl#fBAeLjUSahbV0HBMe54pq45lpSFuOW+Tp11KiOtl9wc=
It's a pdf file with bitcoin addresses.

`^(bc1|[1-9])[a-zA-Z0-9_]{10,40}$	bitcoin_ss`


I added this entry to email.tsv file. The regex seems to work on regex101.
But it is non operative in OSS, while email adresses work like a charm.

**Comment by Mandalka** [comment]
I think it could be the same problem like https://github.com/opensemanticsearch/open-semantic-search/issues/248. Please reopen, if not.
