### ISSUE TITLE
Permission Error while uploading an ontology on Open Semantic Search Server

### ISSUE THREAD

**Issue by mohitsahay** [opensemanticsearch/open-semantic-search#94]
I am using Open Semantic Search Server from https://www.opensemanticsearch.org/download/open-semantic-search_18.02.07.deb and trying to upload an user defined ontology from Manage Structure -> Ontologies -> Add New Ontology. 

After clicking on Save, I am being navigated to a Django Error Page (in attachment) that states - _PermissionError at /ontologies/create
[Errno 13] Permission denied: '/var/solr/data/core1/conf/named_entities/tmp_ocr_dictionary.txt' -> '/etc/opensemanticsearch/ocr/dictionary.txt'_

On disabling Django Debug, all I am getting is 500 error - nothing much in logs that I have.

My basic aim here is to use the ontology for tagging documents which is not happening at present. 
[PermissionError at _ontologies_create.zip](https://github.com/opensemanticsearch/open-semantic-search/files/1718984/PermissionError.at._ontologies_create.zip)

Any assistance or leads on it would be great :)

**Comment by Mandalka** [comment]
Now the missing file system rights for the Django apps are set explicit on installation, so it in future should work without setting rights if package is build from Git repository without not yet set file group rights.

New packages will be available for download later or tomorrow.

**Comment by Mandalka** [comment]
New Debian / Ubuntu server package was build, uploaded and is available for download.

Please reopen, if another rights problem still there, which did not occur on my tests or with my ontologies.

**Comment by mohitsahay** [comment]
Thanks for the quick response!
I have downloaded and used the new package.
The bug is partially resolved in the sense that it is not showing me the Permissions Error now. But there is no affect on applying the Ontology.

Here is what is happening.

After Uploading the Ontology, I am navigated to the page which asks me to Apply the ontology. On applying it, and going back to the search page , I get Apache_Solr_HttpTransportException: '400'.PFB the screenshot.

![ss1](https://user-images.githubusercontent.com/36226362/36295951-9d84d622-1310-11e8-92fa-ed2f73f165b9.png)

I have not changed any of the files, only thing which is done here is just uploading and applying the ontology.

Any leads on it would be really helpful :-)

**Comment by Mandalka** [comment]
Which ontology format do you use?
XML/RDF ? Turtle is not supported (yet).

**Comment by mohitsahay** [comment]
Tried it with owl file and also RDF file.

**Comment by Mandalka** [comment]
Are there label properties in this files?
If public ontologies or not sensitive data, you can send my the ontology by [Email](https://opensemanticsearch.org/contact) so i could test the import.

**Comment by opensemanticsearch** [comment]
In some weeks there will be [more infos on ontology import](https://github.com/opensemanticsearch/open-semantic-search/issues/97).
